-- ====================================================================
-- DISTRIBUIDORA LONDRESS - ESQUEMA Y DATOS INICIALES PARA SUPABASE (POSTGRESQL)
-- ====================================================================
-- INSTRUCCIONES:
-- 1. En tu proyecto de Supabase (https://supabase.com), ve a "SQL Editor".
-- 2. Copia y pega TODO este archivo y haz clic en "Run" (Ejecutar).
-- 3. ¡Listo! Todas las tablas, permisos y tus 28 productos reales quedarán creados.
-- ====================================================================

-- 1. TABLA DE CONSULTAS DE CONTACTO (INQUIRIES)
CREATE TABLE IF NOT EXISTS inquiries (
  _id TEXT PRIMARY KEY,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "businessName" TEXT,
  "contactPerson" TEXT NOT NULL,
  phone TEXT NOT NULL,
  city TEXT,
  "businessType" TEXT,
  message TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending'
);

-- 2. TABLA DE PRODUCTOS
CREATE TABLE IF NOT EXISTS products (
  _id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  sku TEXT,
  "shortDescription" TEXT,
  description TEXT,
  category JSONB,
  brand JSONB,
  images JSONB,
  presentation TEXT,
  specifications JSONB,
  "inStock" BOOLEAN DEFAULT TRUE,
  featured BOOLEAN DEFAULT FALSE,
  "isNew" BOOLEAN DEFAULT FALSE
);

-- 3. TABLA DE CATEGORÍAS
CREATE TABLE IF NOT EXISTS categories (
  _id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  description TEXT,
  image TEXT,
  "itemCount" INTEGER DEFAULT 0
);

-- 4. TABLA DE MARCAS
CREATE TABLE IF NOT EXISTS brands (
  _id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  logo TEXT
);

-- 5. TABLA DE CONFIGURACIÓN DEL SITIO
CREATE TABLE IF NOT EXISTS site_settings (
  id TEXT PRIMARY KEY DEFAULT 'default',
  data JSONB NOT NULL
);

-- GARANTIZAR COLUMNAS IDEMPOTENTES
ALTER TABLE products ADD COLUMN IF NOT EXISTS "featured" BOOLEAN DEFAULT FALSE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS "inStock" BOOLEAN DEFAULT TRUE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS "isNew" BOOLEAN DEFAULT FALSE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS "specifications" JSONB DEFAULT '[]'::jsonb;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS "itemCount" INTEGER DEFAULT 0;

-- HABILITAR ROW LEVEL SECURITY (RLS) Y PERMISOS ABIERTOS
ALTER TABLE inquiries ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE brands ENABLE ROW LEVEL SECURITY;
ALTER TABLE site_settings ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
  DROP POLICY IF EXISTS "Public access to inquiries" ON inquiries;
  CREATE POLICY "Public access to inquiries" ON inquiries FOR ALL USING (true) WITH CHECK (true);

  DROP POLICY IF EXISTS "Public access to products" ON products;
  CREATE POLICY "Public access to products" ON products FOR ALL USING (true) WITH CHECK (true);

  DROP POLICY IF EXISTS "Public access to categories" ON categories;
  CREATE POLICY "Public access to categories" ON categories FOR ALL USING (true) WITH CHECK (true);

  DROP POLICY IF EXISTS "Public access to brands" ON brands;
  CREATE POLICY "Public access to brands" ON brands FOR ALL USING (true) WITH CHECK (true);

  DROP POLICY IF EXISTS "Public access to site_settings" ON site_settings;
  CREATE POLICY "Public access to site_settings" ON site_settings FOR ALL USING (true) WITH CHECK (true);
END $$;

-- 5.1 STORAGE BUCKET PARA FOTOS DE PRODUCTOS
INSERT INTO storage.buckets (id, name, public) 
VALUES ('uploads', 'uploads', true) 
ON CONFLICT (id) DO UPDATE SET public = true;

DO $$ 
BEGIN
  DROP POLICY IF EXISTS "Public Access to uploads" ON storage.objects;
  CREATE POLICY "Public Access to uploads" ON storage.objects FOR SELECT USING (bucket_id = 'uploads');

  DROP POLICY IF EXISTS "Public Insert to uploads" ON storage.objects;
  CREATE POLICY "Public Insert to uploads" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'uploads');

  DROP POLICY IF EXISTS "Public Update to uploads" ON storage.objects;
  CREATE POLICY "Public Update to uploads" ON storage.objects FOR UPDATE USING (bucket_id = 'uploads');

  DROP POLICY IF EXISTS "Public Delete to uploads" ON storage.objects;
  CREATE POLICY "Public Delete to uploads" ON storage.objects FOR DELETE USING (bucket_id = 'uploads');
END $$;

-- 6. CARGA DE CONFIGURACIÓN INICIAL
INSERT INTO site_settings (id, data) 
VALUES ('default', '{"companyName":"Distribuidora Londress","slogan":"Venta y distribución de máquinas e insumos de peluquería, barbería y equipamiento profesional","whatsapp":"5492216733172","phone":"+54 9 221 673-3172","email":"Londressdistri@gmail.com","city":"Buenos Aires, Argentina","schedule":"Lunes a Viernes de 08:30 a 18:00 hs | Sábados de 09:00 a 13:00 hs","heroTitle":"Máquinas e Insumos de Peluquería y Barbería","heroSubtitle":"Provisión integral para salones de belleza, barberías, academias y profesionales. Herramientas de precisión, repuestos originales y cosmética capilar especializada.","heroBadge":"Distribuidor Oficial Barber & Hair Salon","announcementText":"Distribución Oficial de Máquinas e Insumos • Atención Directa a Salones y Barberías al 2216733172","announcementActive":true}'::jsonb)
ON CONFLICT (id) DO UPDATE SET data = EXCLUDED.data;

-- 7. CARGA DE CATEGORÍAS
INSERT INTO categories (_id, title, slug, description, image, "itemCount") VALUES ('cat-maquinas', 'Máquinas de Corte & Trimmers', 'maquinas-corte-trimmers', 'Clippers inalámbricas, trimmers de terminación, shavers de lámina y kits profesionales de marcas líderes.', '/uploads/articulos/wahl-senior-cordless.jpeg', 14) ON CONFLICT (_id) DO NOTHING;
INSERT INTO categories (_id, title, slug, description, image, "itemCount") VALUES ('cat-tijeras', 'Tijeras, Navajas & Filos', 'tijeras-filos-profesionales', 'Tijeras de corte microdentadas, filo dulce Solingen, navajas de barbero y hojas de afeitar profesionales.', '/uploads/articulos/treet-platinum-100-pack.jpeg', 6) ON CONFLICT (_id) DO NOTHING;
INSERT INTO categories (_id, title, slug, description, image, "itemCount") VALUES ('cat-secadores', 'Secadores & Herramientas Térmicas', 'secadores-herramientas-termicas', 'Secadores de alto rendimiento con motor italiano y tecnología cerámica iónica.', '/uploads/articulos/secador-tucano-8600w.jpeg', 1) ON CONFLICT (_id) DO NOTHING;
INSERT INTO categories (_id, title, slug, description, image, "itemCount") VALUES ('cat-accesorios', 'Accesorios, Capas & Barbería', 'accesorios-capas-barberia', 'Capas WMARK, peines de corte, alzas premium, papel de cuello, rociadores y cosmética profesional.', '/uploads/articulos/capa-wmark-negra.jpeg', 16) ON CONFLICT (_id) DO NOTHING;

-- 8. CARGA DE MARCAS
INSERT INTO brands (_id, name, slug, logo) VALUES ('b-londress', 'Londress Pro Series', 'londress-pro', NULL) ON CONFLICT (_id) DO NOTHING;
INSERT INTO brands (_id, name, slug, logo) VALUES ('b-wahl', 'Wahl Professional', 'wahl', NULL) ON CONFLICT (_id) DO NOTHING;
INSERT INTO brands (_id, name, slug, logo) VALUES ('b-babyliss', 'BaBylissPRO', 'babyliss-pro', NULL) ON CONFLICT (_id) DO NOTHING;
INSERT INTO brands (_id, name, slug, logo) VALUES ('b-vgr', 'VGR Professional', 'vgr', NULL) ON CONFLICT (_id) DO NOTHING;
INSERT INTO brands (_id, name, slug, logo) VALUES ('b-wmark', 'WMARK Professional', 'wmark', NULL) ON CONFLICT (_id) DO NOTHING;
INSERT INTO brands (_id, name, slug, logo) VALUES ('b-kemei', 'Kemei Professional', 'kemei', NULL) ON CONFLICT (_id) DO NOTHING;
INSERT INTO brands (_id, name, slug, logo) VALUES ('b-andis', 'Andis USA', 'andis', NULL) ON CONFLICT (_id) DO NOTHING;
INSERT INTO brands (_id, name, slug, logo) VALUES ('b-treet', 'Treet Platinum', 'treet', NULL) ON CONFLICT (_id) DO NOTHING;
INSERT INTO brands (_id, name, slug, logo) VALUES ('b-tucano', 'Tucano Hair Tools', 'tucano', NULL) ON CONFLICT (_id) DO NOTHING;
INSERT INTO brands (_id, name, slug, logo) VALUES ('b-dompelo', 'Dom Pelo', 'dom-pelo', NULL) ON CONFLICT (_id) DO NOTHING;
INSERT INTO brands (_id, name, slug, logo) VALUES ('b-l3vel3', 'L3VEL3', 'l3vel3', NULL) ON CONFLICT (_id) DO NOTHING;
INSERT INTO brands (_id, name, slug, logo) VALUES ('b-infinity', 'Infinity Look''s Hair', 'infinity', NULL) ON CONFLICT (_id) DO NOTHING;
INSERT INTO brands (_id, name, slug, logo) VALUES ('b-jaguar', 'Jaguar Solingen', 'jaguar', NULL) ON CONFLICT (_id) DO NOTHING;
INSERT INTO brands (_id, name, slug, logo) VALUES ('b-derby', 'Derby Professional', 'derby', NULL) ON CONFLICT (_id) DO NOTHING;

-- 9. CARGA DE PRODUCTOS REALES (37 ARTÍCULOS)
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-after-shave-clasica', 'Loción After Shave Clásica Infinity Look''s Hair Menthol 120ml', 'after-shave-clasica-infinity-menthol-120ml', 'INF-AFT-CLAS', 'Loción astringente clásica post-afeitado con acción antiséptica inmediata y frescura mentolada prolongada.', 'La Loción After Shave Clásica Infinity Look''s Hair Menthol ha sido especialmente formulada para salones de barbería y el cuidado post-afeitado más exigente. Su fórmula astringente con alcohol puro cosmético y mentol cristalizado cierra instantáneamente los poros abiertos tras el paso de la navaja o máquina shaver, desinfecta micro-cortes dérmicos e inhibe la proliferación bacteriana causante de la foliculitis. Deja una estela fresca, viril y revitalizante sin sensación grasa.', '{"_id":"cat-accesorios","title":"Accesorios, Capas & Barbería","slug":"accesorios-capas-barberia","description":"Capas WMARK, peines de corte, alzas premium, papel de cuello, rociadores y cosmética profesional.","icon":"Package","image":"/uploads/articulos/capa-wmark-negra.jpeg"}'::jsonb, '{"_id":"b-infinity","name":"Infinity Look''s Hair","slug":"infinity"}'::jsonb, '["/uploads/articulos/infinity-locion-posbarba-menthol.jpeg","/uploads/articulos/infinity-locion-posbarba-2.jpeg"]'::jsonb, 'Frasco PET dosificador de 120 ml', '[{"key":"Presentación","value":"Frasco PET ámbar de 120 ml con pico vertedor ergonómico"},{"key":"Ingredientes Clave","value":"Mentol cristalizado, extracto de hamamelis y alcohol etílico cosmético"},{"key":"Efecto","value":"Cierre de poros, acción antiséptica refrescante y alivio de irritación"},{"key":"Modo de uso","value":"Aplicar unas gotas sobre las palmas y masajear con toques suaves sobre la piel afeitada"},{"key":"Origen","value":"Industria Argentina (fórmula profesional para barberías)"}]'::jsonb, TRUE, TRUE, FALSE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-filos-derby-extra', 'Hojas de Afeitar Derby Extra Professional Single Edge (Caja x 100 Filos)', 'filos-derby-extra-professional-100', 'DRB-EXT-100', 'Filos de acero sueco inoxidable con quíntuple recubrimiento de cromo, cerámica, platino y polímero para un afeitado suave sin tirones.', 'Las hojas de afeitar Derby Extra Professional Single Edge vienen precortadas de fábrica, listas para insertar de forma directa en cualquier porta navaja de barbero sin necesidad de partir la hoja manualmente. Forjadas con acero inoxidable sueco de alta pureza, cada filo pasa por un proceso de recubrimiento quíntuple: cromo para resistencia al óxido, cerámica para duración del filo, platino para suavidad y polímero PTFE para un deslizamiento sedoso sin irritación.', '{"_id":"cat-tijeras","title":"Tijeras, Navajas & Filos","slug":"tijeras-filos-profesionales","description":"Tijeras de corte microdentadas, filo dulce Solingen, navajas de barbero y hojas de afeitar profesionales.","icon":"Sparkles","image":"/uploads/articulos/treet-platinum-100-pack.jpeg"}'::jsonb, '{"_id":"b-derby","name":"Derby Professional","slug":"derby"}'::jsonb, '["/uploads/articulos/navajas-barber-custom.jpeg"]'::jsonb, 'Caja dispensadora con 100 medias hojas descartables (Single Edge)', '[{"key":"Formato","value":"Media hoja partida de fábrica (Single Edge lista para navaja)"},{"key":"Cantidad","value":"100 filos individuales en envase dispensador higiénico"},{"key":"Material","value":"Acero inoxidable sueco templado al vacío"},{"key":"Recubrimiento","value":"Quíntuple capa de Cromo, Cerámica, Platino, Tungsteno y Teflón PTFE"},{"key":"Compatibilidad","value":"Todos los porta navajas estándar de barbería"},{"key":"Filo","value":"Grado de corte suave y tolerante, ideal pieles sensibles"}]'::jsonb, TRUE, FALSE, FALSE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-cepillo-fade', 'Cepillo Fade Brush Barber de Cerdas de Nylon Micro-Densas', 'cepillo-fade-brush-barber-nylon', 'CEP-FAD-BLK', 'Cepillo limpiador de degradados con cerdas ultra suaves que barren el pelo cortado sin raspar ni enrojecer el cuero cabelludo.', 'El Cepillo Fade Brush es la herramienta de precisión indispensable durante cualquier corte con máquina clipper o shaver. Sus cerdas de nylon suave de alta densidad retiran en una sola pasada el cabello microscópico adherido al cuero cabelludo del cliente, permitiendo observar claramente la sombra del desvanecido sin irritar la piel, incluso tras múltiples pasadas continuas.', '{"_id":"cat-accesorios","title":"Accesorios, Capas & Barbería","slug":"accesorios-capas-barberia","description":"Capas WMARK, peines de corte, alzas premium, papel de cuello, rociadores y cosmética profesional.","icon":"Package","image":"/uploads/articulos/capa-wmark-negra.jpeg"}'::jsonb, '{"_id":"b-londress","name":"Londress Series","slug":"londress-pro"}'::jsonb, '["/uploads/articulos/cepillos-fade-brush.jpeg"]'::jsonb, 'Blíster individual con cepillo anatómico de precisión', '[{"key":"Material del Mango","value":"Polímero ABS mate anti-deslizante con agarre anatómico"},{"key":"Cerdas","value":"Nylon micro-fino suave de alta densidad con memoria elástica"},{"key":"Largo Total","value":"14 cm con cabezal compacto para maniobrar en nuca y orejas"},{"key":"Uso Principal","value":"Limpieza y visualización continua de sombras en degrades (fades)"},{"key":"Mantenimiento","value":"Lavable con agua y jabón neutro, apto desinfección con Cool Care"}]'::jsonb, TRUE, TRUE, FALSE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-cepillo-talquero', 'Cepillo Talquero Quita Pelos Barber con Fuelle Dosificador', 'cepillo-talquero-quita-pelos-barber-dosificador', 'CEP-TALQ-01', 'Talquero profesional de cerdas suaves con depósito hermético integrado y botón pulsador dosificador de talco.', 'Práctico e higiénico cepillo talquero diseñado para remover pelos del cuello, hombros y rostro al finalizar el servicio. Cuenta con un depósito interno transparente recargable y un pulsador mecánico ergonómico que dosifica la cantidad exacta de talco refrescante directamente a través de las cerdas, logrando una terminación limpia, suave y confortable para el cliente.', '{"_id":"cat-accesorios","title":"Accesorios, Capas & Barbería","slug":"accesorios-capas-barberia","description":"Capas WMARK, peines de corte, alzas premium, papel de cuello, rociadores y cosmética profesional.","icon":"Package","image":"/uploads/articulos/capa-wmark-negra.jpeg"}'::jsonb, '{"_id":"b-londress","name":"Londress Series","slug":"londress-pro"}'::jsonb, '["/uploads/articulos/cepillos-fade-brush.jpeg"]'::jsonb, 'Caja individual con cepillo talquero recargable', '[{"key":"Capacidad","value":"Depósito recargable de 60 g de talco barberil"},{"key":"Cerdas","value":"Microfibra sintética extra suave antialérgica de fácil limpieza"},{"key":"Mecanismo","value":"Válvula dosificadora de fuelle con pulsador ergonómico central"},{"key":"Base","value":"Plana con apoyo vertical firme para estación de trabajo"},{"key":"Cierre","value":"Tapa a rosca con sello hermético antiderrames"}]'::jsonb, TRUE, FALSE, FALSE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-peine-18cm', 'Peine de Corte Profesional 18cm con Regla Milimétrica Graduada', 'peine-corte-profesional-18cm-regla-milimetrica', 'PN-MIL-18CM', 'Peine de fibra de carbono antiestático de 18 cm con regla métrica grabada con láser para precisión absoluta en laterales y nuca.', 'Peine milimetrado de corte profesional de 18 centímetros, fabricado en compuesto de fibra de carbono de alta resistencia térmica (soporta hasta 230 °C). Su regla milimétrica grabada a láser en el lomo permite medir con exactitud simétrica las alturas de capas, laterales y patillas. Púas redondeadas que cuidan el cuero cabelludo y primer diente recortado para particiones ultrarrápidas.', '{"_id":"cat-accesorios","title":"Accesorios, Capas & Barbería","slug":"accesorios-capas-barberia","description":"Capas WMARK, peines de corte, alzas premium, papel de cuello, rociadores y cosmética profesional.","icon":"Package","image":"/uploads/articulos/capa-wmark-negra.jpeg"}'::jsonb, '{"_id":"b-londress","name":"Londress Series","slug":"londress-pro"}'::jsonb, '["/uploads/articulos/peine-carbono-profesional.jpeg"]'::jsonb, 'Funda protectora individual de vinilo', '[{"key":"Largo","value":"18 cm (7 pulgadas estándar internacional)"},{"key":"Material","value":"Compuesto de fibra de carbono enriquecida antiestática"},{"key":"Graduación","value":"Regla milimétrica en relieve resistente al desgaste químico"},{"key":"Resistencia térmica","value":"Hasta 230 °C (apto secador y planchita)"},{"key":"Dentado","value":"Mixto (fino y medio) con diente guía para secciones"}]'::jsonb, TRUE, FALSE, FALSE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-alzas-plastico', 'Set de Alzas Peines Guía de Plástico Universales #1 al #8', 'set-alzas-peines-guia-plastico-universales', 'ALZ-PLS-UNIV', 'Juego completo de 8 alzas plásticas con calce a presión firme y seguro, compatibles con clippers Wahl, Kemei, VGR y WMARK.', 'Set integral de 8 peines guía fabricados en polímero de ingeniería de alta flexibilidad y resistencia mecánica. Sus dientes redondeados guían el cabello con suavidad hacia la cuchilla sin curvarse ni flexionar durante el paso, garantizando un corte parejo en toda la cabeza. Calce a presión universal apto para la gran mayoría de máquinas de corte estándar del mercado.', '{"_id":"cat-accesorios","title":"Accesorios, Capas & Barbería","slug":"accesorios-capas-barberia","description":"Capas WMARK, peines de corte, alzas premium, papel de cuello, rociadores y cosmética profesional.","icon":"Package","image":"/uploads/articulos/capa-wmark-negra.jpeg"}'::jsonb, '{"_id":"b-londress","name":"Londress Series","slug":"londress-pro"}'::jsonb, '["/uploads/articulos/wahl-peine-guia-premium-05.jpeg"]'::jsonb, 'Blíster sellado con 8 alzas numeradas del 1 al 8 (3 mm a 25 mm)', '[{"key":"Medidas incluidas","value":"#1 (3mm), #2 (6mm), #3 (10mm), #4 (13mm), #5 (16mm), #6 (19mm), #7 (22mm), #8 (25mm)"},{"key":"Material","value":"Polímero termoplástico semi-rígido de alta durabilidad"},{"key":"Compatibilidad","value":"Cuchillas estándar tipo Wahl (Magic Clip, Senior, Super Taper, Kemei 2600, WMARK)"},{"key":"Tipo de agarre","value":"Clip de fijación posterior a presión sin holguras"}]'::jsonb, TRUE, FALSE, FALSE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-cool-care', 'Andis Cool Care Plus 5 in 1 Aerosol Refrigerante para Cuchillas 439g', 'andis-cool-care-plus-5-en-1-439g', 'AND-CCL-439', 'Desinfectante, refrigerante, lubricante, limpiador y antioxidante 5 en 1 para cuchillas de máquinas de corte profesionales.', 'El producto más utilizado en el mundo por barberos profesionales para el mantenimiento preventivo y de alto rendimiento de sus herramientas. Su fórmula virucida, fungicida y bactericida enfría la cuchilla recalentada en solo 5 segundos mediante un chorro de alta presión que expulsa cabellos retenidos, mientras deposita una película de lubricación fina que reduce la fricción y previene la oxidación sin necesidad de desmontar la máquina.', '{"_id":"cat-accesorios","title":"Accesorios, Capas & Barbería","slug":"accesorios-capas-barberia","description":"Capas WMARK, peines de corte, alzas premium, papel de cuello, rociadores y cosmética profesional.","icon":"Package","image":"/uploads/articulos/capa-wmark-negra.jpeg"}'::jsonb, '{"_id":"b-andis","name":"Andis Professional","slug":"andis"}'::jsonb, '["/uploads/articulos/andis-cool-care-plus.jpeg"]'::jsonb, 'Aerosol presurizado de 439 gramos (15.5 oz)', '[{"key":"Funciones","value":"Enfría, desinfecta, lubrica, limpia y previene la corrosión (5 en 1)"},{"key":"Tiempo de enfriamiento","value":"Menos de 5 segundos de aplicación continua"},{"key":"Contenido","value":"439 gramos / 15.5 oz netas"},{"key":"Pico dosificador","value":"Boquilla Comfort Tip de alta presión focalizada"},{"key":"Compatibilidad","value":"Cuchillas de acero al carbono, cromadas, DLC y cerámicas"}]'::jsonb, TRUE, TRUE, FALSE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-gel-para-afeitar', 'Gel de Afeitar Transparente Dom Pelo Shaving Gel Mentolado 500g', 'gel-para-afeitar-transparente-dom-pelo-500g', 'DMP-SHV-500', 'Gel no espumígeno de máxima transparencia con mentol y aloe vera para perfilado milimétrico de barba y contornos.', 'Especialmente formulado para trabajos de precisión en barbería. A diferencia de las espumas tradicionales que tapan la línea de corte, la textura 100% cristalina del gel Dom Pelo permite al profesional ver exactamente por dónde desliza la navaja o cuchilla. Sus activos emolientes ablandan el vello grueso al instante y crean una película deslizante protectora que reduce la fricción y el enrojecimiento.', '{"_id":"cat-accesorios","title":"Accesorios, Capas & Barbería","slug":"accesorios-capas-barberia","description":"Capas WMARK, peines de corte, alzas premium, papel de cuello, rociadores y cosmética profesional.","icon":"Package","image":"/uploads/articulos/capa-wmark-negra.jpeg"}'::jsonb, '{"_id":"b-dompelo","name":"Dom Pelo","slug":"dom-pelo"}'::jsonb, '["/uploads/articulos/dom-pelo-shaving-gel-500g.jpeg"]'::jsonb, 'Pote con válvula dosificadora de 500 gramos', '[{"key":"Contenido Neto","value":"500 gramos con dispensador pump"},{"key":"Fórmula","value":"100% transparente cristalina no espumígena"},{"key":"Principios Activos","value":"Mentol estimulante, glicerina humectante y aloe vera calmante"},{"key":"Aplicación","value":"Perfilado de barba, contorno de cuello, nuca y cabeza completa"},{"key":"Sensación","value":"Frescura intensa de efecto descongestivo"}]'::jsonb, TRUE, TRUE, FALSE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-porta-navaja', 'Porta Navaja de Barbero Profesional Londress Series', 'porta-navaja-barbero-profesional-londress', 'NVJ-PRO-CUST', 'Porta navaja de barbero con brazo de acero inoxidable 420 y clip de bloqueo de seguridad para medias hojas descartables.', 'Fabricada para ofrecer un equilibrio de peso perfecto entre el mango anatómico y el brazo portante. Su sistema de traba oscilante con pestaña de presión sujeta la media hoja de afeitar con firmeza milimétrica, impidiendo cualquier desvío o movimiento durante el afeitado al ras o el delineado de cejas y patillas.', '{"_id":"cat-tijeras","title":"Tijeras, Navajas & Filos","slug":"tijeras-filos-profesionales","description":"Tijeras de corte microdentadas, filo dulce Solingen, navajas de barbero y hojas de afeitar profesionales.","icon":"Sparkles","image":"/uploads/articulos/treet-platinum-100-pack.jpeg"}'::jsonb, '{"_id":"b-londress","name":"Londress Series","slug":"londress-pro"}'::jsonb, '["/uploads/articulos/navajas-barber-custom.jpeg"]'::jsonb, 'Estuche individual con porta navaja de precisión', '[{"key":"Material del Brazo","value":"Acero inoxidable quirúrgico 420 anticorrosión"},{"key":"Cierre","value":"Clip basculante con traba de presión reforzada anti-vibración"},{"key":"Largo","value":"Abierto: 21.5 cm | Plegado: 14 cm"},{"key":"Compatibilidad de Hoja","value":"Media hoja descartable estándar (Derby, Treet, Gillette)"},{"key":"Acabado","value":"Grabado láser de alta durabilidad resistente a desinfectantes"}]'::jsonb, TRUE, FALSE, FALSE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-secador-tucano', 'Secador Profesional Tucano HairDryer 8600 Watt Motor AC Italiano', 'secador-profesional-tucano-hairdryer-8600w', 'TUC-HDR-8600', 'Secador de salón de alta potencia con motor AC italiano de servicio continuo, tecnología iónica y selector de golpe frío.', 'Herramienta de secado de alto rendimiento construida para soportar jornadas ininterrumpidas en salones y barberías. Su potente motor de corriente alterna genera un flujo de aire concentrado de alta velocidad que acelera los tiempos de secado a la mitad, mientras que su rejilla frontal revestida en cerámica iónica neutraliza la electricidad estática y sella la cutícula capilar.', '{"_id":"cat-secadores","title":"Secadores & Herramientas Térmicas","slug":"secadores-herramientas-termicas","description":"Secadores de alto rendimiento con motor italiano y tecnología cerámica iónica.","icon":"Wind","image":"/uploads/articulos/secador-tucano-8600w.jpeg"}'::jsonb, '{"_id":"b-tucano","name":"Tucano Professional","slug":"tucano"}'::jsonb, '["/uploads/articulos/secador-tucano-8600w.jpeg"]'::jsonb, 'Caja oficial con secador, 2 boquillas de modelado y manual técnico', '[{"key":"Potencia Máxima","value":"8600 W referencia técnica de caudal térmico"},{"key":"Tipo de Motor","value":"AC Italiano de larga vida útil (más de 2.000 horas continuas)"},{"key":"Velocidades y Temperaturas","value":"2 velocidades de soplado y 3 niveles de temperatura"},{"key":"Botón de Frío","value":"Golpe de frío instantáneo para sellar cutícula y peinado"},{"key":"Cable","value":"Profesional reforzado de 2.5 metros con ojal para colgar"},{"key":"Accesorios","value":"2 boquillas concentradoras de aire (estrecha y ancha)"}]'::jsonb, TRUE, TRUE, FALSE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-vgr-938', 'Trimmer Corporal VGR V-938 Edición Oficial AFA Selección Argentina', 'trimmer-corporal-vgr-v938-edicion-afa', 'VGR-V938-AFA', 'Trimmer corporal y de terminación con cuchilla cerámica Skin-Safe anticortes, luz LED de precisión y resistencia al agua IPX7.', 'La VGR V-938 combina la licencia oficial de la Asociación del Fútbol Argentino con la más avanzada tecnología para rasurado corporal y de terminación. Cuenta con una cuchilla móvil cerámica con diseño redondeado Skin-Safe que evita pellizcos e irritaciones en zonas delicadas, linterna frontal LED de iluminación directa y batería de litio recargable con base de acople vertical.', '{"_id":"cat-maquinas","title":"Máquinas de Corte & Trimmers","slug":"maquinas-corte-trimmers","description":"Clippers inalámbricas, trimmers de terminación, shavers de lámina y kits profesionales de marcas líderes.","icon":"Scissors","image":"/uploads/articulos/wahl-senior-cordless.jpeg"}'::jsonb, '{"_id":"b-vgr","name":"VGR Professional","slug":"vgr"}'::jsonb, '["/uploads/articulos/vgr-v938-afa-trimmer.jpeg"]'::jsonb, 'Caja premium oficial AFA con base de carga, cable USB y peines guía', '[{"key":"Cuchilla","value":"Cerámica Skin-Safe hipoalergénica con puntas redondeadas anti-cortes"},{"key":"Iluminación","value":"Luz LED frontal integrada para visualización de precisión"},{"key":"Resistencia al agua","value":"Certificación IPX7 100% lavable bajo la canilla"},{"key":"Batería","value":"Iones de litio de 600 mAh (hasta 90 minutos de uso)"},{"key":"Carga","value":"Base vertical de apoyo o conexión directa USB Tipo-C"},{"key":"Diseño","value":"Licencia oficial AFA Campeones del Mundo con escudo dorado"}]'::jsonb, TRUE, TRUE, TRUE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-vgr-011', 'Máquina de Corte VGR Navigator V-011 Professional Clipper', 'maquina-corte-vgr-navigator-v011', 'VGR-V011', 'Clipper inalámbrica con motor de alto torque de 6.500 RPM, display LED con indicador porcentual de batería y cuchilla semiplana.', 'La VGR Navigator V-011 es una máquina de corte robusta y confiable, ideal para barberos que buscan potencia y autonomía sin cables a un valor inigualable. Su cuchilla de acero inoxidable de alta retención de filo trabaja en conjunto con una palanca de ajuste lateral metálica para transiciones limpias y fluidas. Pantalla digital que informa el porcentaje exacto de batería restante.', '{"_id":"cat-maquinas","title":"Máquinas de Corte & Trimmers","slug":"maquinas-corte-trimmers","description":"Clippers inalámbricas, trimmers de terminación, shavers de lámina y kits profesionales de marcas líderes.","icon":"Scissors","image":"/uploads/articulos/wahl-senior-cordless.jpeg"}'::jsonb, '{"_id":"b-vgr","name":"VGR Professional","slug":"vgr"}'::jsonb, '["/uploads/articulos/vgr-v011-clipper.jpeg","/uploads/articulos/vgr-v011-clipper-2.jpeg","/uploads/articulos/vgr-v011-clipper-3.jpeg"]'::jsonb, 'Caja de lujo con máquina, 4 peines guía, cable USB, cepillo y lubricante', '[{"key":"Motor","value":"Rotativo de alto torque 6.500 RPM constante"},{"key":"Cuchilla","value":"Acero inoxidable cromado con microdentado Fade"},{"key":"Batería","value":"Litio de 2.000 mAh (hasta 180 minutos continuos)"},{"key":"Display","value":"Pantalla LCD digital con nivel de carga y aviso de lubricación"},{"key":"Palanca de ajuste","value":"Regulable de 0.8 mm a 2.0 mm con clics definidos"},{"key":"Peines guía incluidos","value":"4 peines reforzados (3, 6, 9 y 12 mm)"}]'::jsonb, TRUE, FALSE, FALSE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-vgr-275', 'Trimmer VGR Voyager V-275 Professional Hair Trimmer Gold', 'trimmer-vgr-voyager-v275-gold', 'VGR-V275', 'Trimmer de terminación inalámbrico con cuerpo tallado vintage en relieve dorado, cuchilla T-Blade y motor de 6.500 RPM.', 'Con su exclusivo cuerpo vintage en relieve dorado y su cuchilla en forma de T con corte al ras (0.1 mm), la VGR Voyager V-275 es ideal para dibujos, contornos de barba, patillas y nuca. Su cabezal suspendido expuesto a 360° ofrece una visión nítida de la línea de corte en cualquier ángulo de trabajo.', '{"_id":"cat-maquinas","title":"Máquinas de Corte & Trimmers","slug":"maquinas-corte-trimmers","description":"Clippers inalámbricas, trimmers de terminación, shavers de lámina y kits profesionales de marcas líderes.","icon":"Scissors","image":"/uploads/articulos/wahl-senior-cordless.jpeg"}'::jsonb, '{"_id":"b-vgr","name":"VGR Professional","slug":"vgr"}'::jsonb, '["/uploads/articulos/vgr-v275-trimmer-gold.jpeg"]'::jsonb, 'Caja metálica de presentación con trimmer, 3 peines guía, cable y aceite', '[{"key":"Cuerpo","value":"Metal fundido con grabado artístico vintage en dorado"},{"key":"Cuchilla","value":"T-Blade quirúrgica de acero al carbono de 40 mm expuesta 360°"},{"key":"Corte mínimo","value":"0.1 mm (zero-gap estricto para líneas definidas)"},{"key":"Batería","value":"Iones de litio (hasta 150 minutos de autonomía)"},{"key":"Conexión","value":"Carga rápida USB Tipo-C universal"},{"key":"Accesorios","value":"3 peines de alza (1 mm, 2 mm, 3 mm) y cepillo de limpieza"}]'::jsonb, TRUE, FALSE, FALSE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-rociador', 'Rociador Pulverizador Barber Design Pico Regulable 300ml', 'rociador-pulverizador-barber-design-300ml', 'ROC-PLV-BAR', 'Atomizador pulverizador ergonómico con depósito de 300 ml y boquilla regulable de niebla ultrafina a chorro continuo.', 'Rociador de agua profesional para humedecer el cabello antes del corte con tijera o máquina. Su gatillo de acción suave con resorte de retorno rápido reduce la fatiga en los dedos durante jornadas largas. Cuenta con boquilla de bronce/plástico regulable que permite seleccionar desde una bruma pulverizada ultra uniforme hasta un chorro directo.', '{"_id":"cat-accesorios","title":"Accesorios, Capas & Barbería","slug":"accesorios-capas-barberia","description":"Capas WMARK, peines de corte, alzas premium, papel de cuello, rociadores y cosmética profesional.","icon":"Package","image":"/uploads/articulos/capa-wmark-negra.jpeg"}'::jsonb, '{"_id":"b-londress","name":"Londress Series","slug":"londress-pro"}'::jsonb, '["/uploads/articulos/rociadores-barber-transparentes.jpeg"]'::jsonb, 'Botella plástica transparente serigrafiada con gatillo atomizador', '[{"key":"Capacidad","value":"300 ml con escala de nivel visible"},{"key":"Gatillo","value":"Ergonómico de doble pulsación suave con resorte reforzado"},{"key":"Boquilla","value":"Regulable (niebla ultrafina o chorro direccional)"},{"key":"Material","value":"Plástico PET de alto impacto resistente a químicos de salón"},{"key":"Diseño","value":"Gráfica serigrafiada temática barbería clásica de alta nitidez"}]'::jsonb, TRUE, FALSE, FALSE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-peine-plastico', 'Peine Plástico de Corte Profesional Barber Series', 'peine-plastico-corte-profesional-barber', 'PN-PLS-BAR', 'Peine de corte plástico flexible y ligero de alta durabilidad, con doble dentado fino y grueso para todo tipo de cabello.', 'Peine clásico de salón confeccionado en polímero termoplástico flexible de gran resistencia al impacto y al agua. Su diseño de dos zonas dentadas permite peinar tanto melenas densas como desenredar secciones delgadas previas a la tijera, sin tirones ni electricidad estática.', '{"_id":"cat-accesorios","title":"Accesorios, Capas & Barbería","slug":"accesorios-capas-barberia","description":"Capas WMARK, peines de corte, alzas premium, papel de cuello, rociadores y cosmética profesional.","icon":"Package","image":"/uploads/articulos/capa-wmark-negra.jpeg"}'::jsonb, '{"_id":"b-londress","name":"Londress Series","slug":"londress-pro"}'::jsonb, '["/uploads/articulos/peines-carbono-dorado.jpeg"]'::jsonb, 'Unidad individual en funda de protección', '[{"key":"Material","value":"Polímero termoplástico de alta tenacidad y flexibilidad"},{"key":"Dentado","value":"Doble sección (dientes medios desenredantes y dientes finos de tensión)"},{"key":"Largo","value":"20 cm de alcance equilibrado"},{"key":"Puntas","value":"Púas pulidas y redondeadas anti-arañazos en cuero cabelludo"},{"key":"Uso","value":"Corte a tijera, desenredo rápido y peinado en húmedo"}]'::jsonb, TRUE, FALSE, FALSE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-peine-metal', 'Peine Metálico Profesional Barber Edición Gold de Precisión', 'peine-metalico-profesional-gold-barber', 'PN-MET-GLD', 'Peine de aluminio aeronáutico anodizado en dorado, ultraligero e indeformable para detalles de terminación y barbas.', 'Fabricado en aluminio macizo con baño galvánico dorado resistente a la corrosión y a desinfectantes. No se deforma, no se parte y no genera estática en ningún tipo de cabello. Su peso equilibrado y su acabado suave al tacto ofrecen una experiencia de peinado premium y gran presencia en la estación de trabajo.', '{"_id":"cat-accesorios","title":"Accesorios, Capas & Barbería","slug":"accesorios-capas-barberia","description":"Capas WMARK, peines de corte, alzas premium, papel de cuello, rociadores y cosmética profesional.","icon":"Package","image":"/uploads/articulos/capa-wmark-negra.jpeg"}'::jsonb, '{"_id":"b-londress","name":"Londress Series","slug":"londress-pro"}'::jsonb, '["/uploads/articulos/peines-carbono-dorado.jpeg"]'::jsonb, 'Estuche individual protector', '[{"key":"Material","value":"Aleación de aluminio aeronáutico anodizado quirúrgico"},{"key":"Acabado","value":"Dorado satinado de alta durabilidad anti-rayas"},{"key":"Propiedad","value":"100% libre de estática (anti-frizz natural)"},{"key":"Resistencia","value":"Inmune al calor, alcoholes, químicos y tinturas"},{"key":"Puntas","value":"Púas fresadas con extremos esféricos suaves"}]'::jsonb, TRUE, FALSE, FALSE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-after-level3', 'Colonia Post-Afeitado L3VEL3 Aftershave Cologne Vibrant 400ml', 'colonia-aftershave-l3vel3-vibrant-400ml', 'LV3-AFT-400', 'Colonia aftershave americana de fijación prolongada que hidrata la piel, cierra los poros y deja una fragancia intensa y sofisticada.', 'La colonia L3VEL3 Aftershave Vibrant combina el poder antiséptico y calmante de un post-afeitado con la estela duradera de una colonia de perfumería fina. Calma la quemazón de la navaja en segundos, hidrata la piel evitando la resequedad y brinda a tus clientes esa fragancia moderna y distintiva que caracteriza a los salones de primer nivel internacional.', '{"_id":"cat-accesorios","title":"Accesorios, Capas & Barbería","slug":"accesorios-capas-barberia","description":"Capas WMARK, peines de corte, alzas premium, papel de cuello, rociadores y cosmética profesional.","icon":"Package","image":"/uploads/articulos/capa-wmark-negra.jpeg"}'::jsonb, '{"_id":"b-l3vel3","name":"L3VEL3 Professional","slug":"l3vel3"}'::jsonb, '["/uploads/articulos/l3vel3-aftershave-vibrant.jpeg"]'::jsonb, 'Botella de 400 ml con pico vertedor', '[{"key":"Contenido","value":"400 ml / 13.5 fl oz en envase profesional"},{"key":"Fragancia","value":"Vibrant (notas cítricas, maderas nobles y ámbar fresco)"},{"key":"Acción","value":"Cierra los poros, hidrata y desinfecta la piel recién afeitada"},{"key":"Presentación","value":"Botella plástica ergonómica con tapa dosificadora"},{"key":"Origen","value":"Fórmula profesional L3VEL3 USA"}]'::jsonb, TRUE, TRUE, FALSE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-alzas-05', 'Peine Guía WAHL Premium Cutting Guide # 1/2 con Traba Metálica 1.5mm', 'alza-wahl-premium-05-15mm-traba-metalica', 'WHL-PG-05', 'Peine guía Wahl original de 1.5 mm (#0.5) con clip de enganche metálico de acero inoxidable para calce sin holguras.', 'El alza más crítica en la técnica del degradado moderno. El peine guía Wahl # 1/2 (1.5 mm) permite conectar de forma invisible la transición entre la máquina a cero abierta y el número 1 cerrado. Su clip posterior de acero templado garantiza que el peine quede completamente fijo a la cuchilla, eliminando cualquier riesgo de desprendimiento accidental durante el corte.', '{"_id":"cat-accesorios","title":"Accesorios, Capas & Barbería","slug":"accesorios-capas-barberia","description":"Capas WMARK, peines de corte, alzas premium, papel de cuello, rociadores y cosmética profesional.","icon":"Package","image":"/uploads/articulos/capa-wmark-negra.jpeg"}'::jsonb, '{"_id":"b-wahl","name":"Wahl Professional","slug":"wahl"}'::jsonb, '["/uploads/articulos/wahl-peine-guia-premium-05.jpeg","/uploads/articulos/wahl-peine-guia-premium-05-2.jpeg"]'::jsonb, 'Blíster oficial individual Wahl Premium', '[{"key":"Medida","value":"# 1/2 (1.5 mm - 1/16 de pulgada)"},{"key":"Traba","value":"Clip de acero inoxidable templado con resorte de alta tensión"},{"key":"Material","value":"Polímero plástico de ingeniería con fibra de vidrio anti-deformación"},{"key":"Dientes","value":"Redondeados para deslizamiento suave sobre el cuero cabelludo"},{"key":"Compatibilidad","value":"Clippers Wahl estándar (Magic Clip, Senior, Super Taper, Legend)"}]'::jsonb, TRUE, TRUE, FALSE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-magic-clip-red', 'Máquina Wahl 5-Star Cordless Magic Clip Red Clásica', 'maquina-wahl-cordless-magic-clip-red-clasica', 'WHL-MGC-RED', 'La clipper de desvanecido más famosa del mundo con cuchilla patentada Stagger-Tooth Crunch y motor rotativo de 5.500 RPM.', 'La Wahl 5-Star Cordless Magic Clip en su icónico acabado borgoña es la máquina de cabecera de las mejores barberías del mundo. Su revolucionaria cuchilla Stagger-Tooth con dientes alternados emite el característico sonido ''Crunch'' que le permite al profesional escuchar con precisión cómo y cuándo el cabello está siendo difuminado. Extremadamente ligera (290 gramos) para jornadas prolongadas sin fatiga.', '{"_id":"cat-maquinas","title":"Máquinas de Corte & Trimmers","slug":"maquinas-corte-trimmers","description":"Clippers inalámbricas, trimmers de terminación, shavers de lámina y kits profesionales de marcas líderes.","icon":"Scissors","image":"/uploads/articulos/wahl-senior-cordless.jpeg"}'::jsonb, '{"_id":"b-wahl","name":"Wahl Professional","slug":"wahl"}'::jsonb, '["/uploads/articulos/wahl-senior-cordless.jpeg"]'::jsonb, 'Caja individual oficial con cargador, 8 peines guía, peine flat top, aceite y cepillo', '[{"key":"Motor","value":"Rotativo profesional de 5.500 RPM continuo"},{"key":"Cuchilla","value":"Stagger-Tooth 2161 Crunch Blade de acero cromado"},{"key":"Batería","value":"Iones de litio sin efecto memoria (100 minutos de uso)"},{"key":"Tiempo de carga","value":"120 minutos para carga completa"},{"key":"Peso","value":"290 gramos (diseño ultraligero sin fatiga en muñeca)"},{"key":"Largo de corte","value":"0.8 mm a 2.5 mm regulable con palanca lateral"}]'::jsonb, TRUE, TRUE, FALSE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-magic-clip-black', 'Máquina Wahl 5-Star Cordless Magic Clip Black & Gold Edition', 'maquina-wahl-cordless-magic-clip-black-gold', 'WHL-MGC-BG', 'Edición premium de la Magic Clip con motor potenciado a 6.500 RPM, cuchillas con revestimiento de titanio y DLC y base de carga.', 'Versión potenciada y elegante de la legendaria Magic Clip. Incorpora un motor más potente de 6.500 RPM y cuchillas bañadas en Titanio Dorado y DLC (Diamond-Like Carbon) que disipan el calor hasta un 40% más eficientemente y multiplican la resistencia al desgaste. Incluye base de recarga vertical con contacto rápido.', '{"_id":"cat-maquinas","title":"Máquinas de Corte & Trimmers","slug":"maquinas-corte-trimmers","description":"Clippers inalámbricas, trimmers de terminación, shavers de lámina y kits profesionales de marcas líderes.","icon":"Scissors","image":"/uploads/articulos/wahl-senior-cordless.jpeg"}'::jsonb, '{"_id":"b-wahl","name":"Wahl Professional","slug":"wahl"}'::jsonb, '["/uploads/articulos/wahl-magic-clip-black-gold.jpeg","/uploads/articulos/wahl-magic-clip-black-gold-2.jpeg"]'::jsonb, 'Caja de edición especial Black & Gold con base de carga, 8 alzas premium, cargador y accesorios', '[{"key":"Motor","value":"Rotativo potenciado a 6.500 RPM de alto rendimiento"},{"key":"Cuchilla","value":"Stagger-Tooth con recubrimiento de Titanio Dorado y DLC antifricción"},{"key":"Batería","value":"Litio de 2.600 mAh (más de 100 minutos de autonomía)"},{"key":"Estación de carga","value":"Base vertical ponderada de contacto dorado incluida"},{"key":"Palanca","value":"Metálica de micro-ajuste de altura con clic firme"},{"key":"Peso","value":"290 gramos"}]'::jsonb, TRUE, TRUE, TRUE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-wahl-senior', 'Máquina Wahl Professional 5-Star Cordless Senior Metal Case', 'maquina-wahl-cordless-senior-metal-case', 'WHL-SNR-01', 'La máquina inalámbrica más potente de Wahl con carcasa inferior de aluminio y motor rotativo V9000 a 7.000 RPM.', 'La Wahl Cordless Senior es la bestia de carga pesada de Wahl. Su carcasa inferior de aluminio fundido absorbe las vibraciones y ofrece una sensación de robustez inigualable en la mano. Su motor de alto torque corta con facilidad cabellos gruesos, húmedos o enmarañados sin atascarse. Equipada con cuchilla quirúrgica Fade Blade ajustable a cero (zero-gap).', '{"_id":"cat-maquinas","title":"Máquinas de Corte & Trimmers","slug":"maquinas-corte-trimmers","description":"Clippers inalámbricas, trimmers de terminación, shavers de lámina y kits profesionales de marcas líderes.","icon":"Scissors","image":"/uploads/articulos/wahl-senior-cordless.jpeg"}'::jsonb, '{"_id":"b-wahl","name":"Wahl Professional","slug":"wahl"}'::jsonb, '["/uploads/articulos/wahl-senior-cordless.jpeg","/uploads/articulos/wahl-senior-cordless-2.jpeg"]'::jsonb, 'Caja oficial Wahl con 3 alzas premium (#1/2, #1, #1 1/2), cargador y aceite', '[{"key":"Motor","value":"Rotativo de alto torque V9000 a 7.000 RPM continuo"},{"key":"Carcasa","value":"Base metálica de aluminio macizo Heavy Duty"},{"key":"Cuchilla","value":"Fade Blade quirúrgica de acero cromado ajustable a 0 gap"},{"key":"Batería","value":"Iones de litio de alta densidad (80 minutos continuo)"},{"key":"Rango de corte","value":"0.5 mm a 1.2 mm de alta precisión"},{"key":"Peso","value":"365 gramos con centro de gravedad balanceado"}]'::jsonb, TRUE, TRUE, FALSE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-wmark-ng-xl', 'Máquina de Corte WMARK NG-XL Professional High-Speed Clipper', 'maquina-corte-wmark-ng-xl-vectorial', 'WMK-NG-XL', 'Clipper de última generación con motor magnético vectorial de 9.000 RPM con microchip inteligente que aumenta la potencia según densidad.', 'La WMARK NG-XL representa el salto a los motores vectoriales en barbería. Su microchip interno sensa la resistencia del cabello y eleva automáticamente el torque del motor de 9.000 RPM cuando atraviesa secciones densas de cabello, garantizando pasadas limpias sin tirones. Cuchilla DLC negra combinada con móvil de cerámica para trabajo en frío durante horas.', '{"_id":"cat-maquinas","title":"Máquinas de Corte & Trimmers","slug":"maquinas-corte-trimmers","description":"Clippers inalámbricas, trimmers de terminación, shavers de lámina y kits profesionales de marcas líderes.","icon":"Scissors","image":"/uploads/articulos/wahl-senior-cordless.jpeg"}'::jsonb, '{"_id":"b-wmark","name":"WMARK Professional","slug":"wmark"}'::jsonb, '["/uploads/articulos/wmark-ng8634-barber-kit.jpeg"]'::jsonb, 'Caja rígida con máquina, base de recarga vertical, cuchilla DLC cerámica, 6 alzas magnéticas y cable', '[{"key":"Motor","value":"Magnético Vectorial controlado por microchip inteligente (9.000 RPM)"},{"key":"Cuchilla","value":"Fija DLC Black Diamond + Móvil Cerámica de Zirconio"},{"key":"Batería","value":"Litio de 2.500 mAh (150 a 180 minutos de uso)"},{"key":"Base de carga","value":"Base vertical con luces de estado LED"},{"key":"Alzas","value":"6 peines magnéticos reforzados con imán de neodimio"},{"key":"Nivel sonoro","value":"Menos de 60 dB en máxima velocidad"}]'::jsonb, TRUE, TRUE, TRUE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-babyliss-gold', 'Trimmer BaBylissPRO FXONE All-Metal Li-ion Gold Edition', 'trimmer-babylisspro-fxone-gold-edition', 'BBY-FXONE-GLD', 'Trimmer totalmente metálico con motor digital sin escobillas N1 de 7.200 RPM y sistema de batería intercambiable FXONE.', 'El buque insignia de BaBylissPRO para terminaciones, líneas y afeitados al ras. Su cuerpo completamente metálico con moleteado diamante brinda un agarre antideslizante insuperable. Su innovador sistema FXONE permite quitar la batería con un botón para reemplazarla en segundos sin interrumpir el trabajo. Cuchilla dorada expuesta a 360 grados con ajuste a cero estricto.', '{"_id":"cat-maquinas","title":"Máquinas de Corte & Trimmers","slug":"maquinas-corte-trimmers","description":"Clippers inalámbricas, trimmers de terminación, shavers de lámina y kits profesionales de marcas líderes.","icon":"Scissors","image":"/uploads/articulos/wahl-senior-cordless.jpeg"}'::jsonb, '{"_id":"b-babyliss","name":"BaBylissPRO","slug":"babyliss-pro"}'::jsonb, '["/uploads/articulos/babylisspro-fxone-gold.jpeg"]'::jsonb, 'Caja de lujo con trimmer, batería FXONE universal, base de carga dual, cuchilla T-Blade 360° y llave de ajuste', '[{"key":"Motor","value":"Digital N1 Brushless (sin escobillas) de 7.200 RPM"},{"key":"Cuchilla","value":"T-Blade dorada expuesta 360° con ajuste a cero milimétrico"},{"key":"Batería","value":"Sistema FXONE modular intercambiable de iones de litio"},{"key":"Autonomía","value":"Hasta 2.5 horas de uso continuo por batería"},{"key":"Cuerpo","value":"Metal macizo moleteado con recubrimiento dorado electrodepositado"},{"key":"Tapa","value":"Bisagra magnética de liberación rápida para limpieza interna"}]'::jsonb, TRUE, TRUE, TRUE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-babyliss-black', 'Trimmer BaBylissPRO FXONE All-Metal Li-ion Black Edition', 'trimmer-babylisspro-fxone-black-edition', 'BBY-FXONE-BLK', 'Terminadora profesional en acabado negro mate con motor digital sin escobillas a 7.200 RPM y cuchilla T-Blade de grafito DLC.', 'La variante Black Edition del sistema FXONE cuenta con una cuchilla en T revestida en Grafito DLC que ofrece un coeficiente de fricción casi nulo, no levanta temperatura y mantiene un filo quirúrgico durante meses. Su motor N1 sin escobillas entrega torque constante independientemente del nivel de carga de la batería.', '{"_id":"cat-maquinas","title":"Máquinas de Corte & Trimmers","slug":"maquinas-corte-trimmers","description":"Clippers inalámbricas, trimmers de terminación, shavers de lámina y kits profesionales de marcas líderes.","icon":"Scissors","image":"/uploads/articulos/wahl-senior-cordless.jpeg"}'::jsonb, '{"_id":"b-babyliss","name":"BaBylissPRO","slug":"babyliss-pro"}'::jsonb, '["/uploads/articulos/babylisspro-fxone-black.jpeg"]'::jsonb, 'Caja premium con trimmer Black Edition, batería intercambiable FXONE, base y herramientas', '[{"key":"Motor","value":"Digital sin carbones de 7.200 RPM constante"},{"key":"Cuchilla","value":"T-Blade Black Graphite DLC (revestimiento de carbono de alta dureza)"},{"key":"Sistema de energía","value":"Batería modular FXONE intercambiable al instante"},{"key":"Autonomía","value":"150 minutos de funcionamiento continuo"},{"key":"Acabado","value":"Negro mate electrochapado anti-rayaduras con grip moleteado"},{"key":"Compatibilidad","value":"Baterías y cargadores compartidos con toda la línea FXONE"}]'::jsonb, TRUE, TRUE, TRUE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-afeitadora-wmark', 'Afeitadora Shaver WMARK NG-8906 High Speed Barber Shaver 9500 RPM', 'afeitadora-shaver-wmark-ng8906-9500rpm', 'WMK-NG8906', 'Shaver profesional de doble lámina de titanio dorado hipoalergénica con motor ultrarrápido de 9.500 RPM para afeitado a piel cero.', 'Diseñada para pulir los degradados más altos y lograr una piel absolutamente suave al ras. Sus dos láminas flotantes independientes de titanio dorado hipoalergénico no causan irritación ni quemaduras en cuellos sensibles. Impulsada por un potente micromotor de 9.500 RPM que afeita tanto en seco como con loción previa.', '{"_id":"cat-maquinas","title":"Máquinas de Corte & Trimmers","slug":"maquinas-corte-trimmers","description":"Clippers inalámbricas, trimmers de terminación, shavers de lámina y kits profesionales de marcas líderes.","icon":"Scissors","image":"/uploads/articulos/wahl-senior-cordless.jpeg"}'::jsonb, '{"_id":"b-wmark","name":"WMARK Professional","slug":"wmark"}'::jsonb, '["/uploads/articulos/wmark-ng8906-shaver.jpeg","/uploads/articulos/wmark-ng8906-shaver-2.jpeg"]'::jsonb, 'Caja con afeitadora shaver, láminas de repuesto, cable USB y cepillo', '[{"key":"Motor","value":"Rotativo de alta velocidad a 9.500 RPM"},{"key":"Cabezal","value":"Doble lámina flotante escalonada de titanio dorado hipoalergénico"},{"key":"Batería","value":"Iones de litio de 1.400 mAh (120 minutos de uso)"},{"key":"Carga","value":"USB Tipo-C de carga rápida"},{"key":"Carcasa","value":"Polímero reforzado con diseño texturado de agarre seguro"},{"key":"Corte mínimo","value":"0.0 mm (efecto piel pulida a navaja)"}]'::jsonb, TRUE, TRUE, FALSE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-afeitadora-vgr325', 'Afeitadora Rotativa VGR V-325 Men''s Shaver Triple Cabezal 3D', 'afeitadora-rotativa-vgr-v325-triple-cabezal', 'VGR-V325', 'Afeitadora eléctrica rotativa con 3 cabezales flotantes independientes 3D, resistencia al agua IPX7 y trimmer patillero desplegable.', 'Afeitadora rotativa versátil para barba, cuello y cabeza completa. Sus 3 cuchillas rotativas con anillos dobles se adaptan automáticamente a los contornos de la mandíbula y el cráneo sin ejercer presión excesiva. Cuenta con trimmer retráctil posterior para emparejar patillas y display digital de batería.', '{"_id":"cat-maquinas","title":"Máquinas de Corte & Trimmers","slug":"maquinas-corte-trimmers","description":"Clippers inalámbricas, trimmers de terminación, shavers de lámina y kits profesionales de marcas líderes.","icon":"Scissors","image":"/uploads/articulos/wahl-senior-cordless.jpeg"}'::jsonb, '{"_id":"b-vgr","name":"VGR Professional","slug":"vgr"}'::jsonb, '["/uploads/articulos/vgr-v315-shaver.jpeg"]'::jsonb, 'Caja con afeitadora, cable de carga USB, cobertor de cabezal y cepillo', '[{"key":"Sistema de afeitado","value":"Triple cabezal rotativo flotante 3D con doble pista de corte"},{"key":"Resistencia al agua","value":"Certificación IPX7 lavable bajo el agua"},{"key":"Autonomía","value":"Hasta 90 minutos de uso ininterrumpido"},{"key":"Patillera","value":"Trimmer desplegable pop-up integrado en el lomo"},{"key":"Pantalla","value":"LED indicador de porcentaje y bloqueo de viaje"},{"key":"Carga","value":"USB universal con carga rápida"}]'::jsonb, TRUE, FALSE, FALSE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-jaguar-entresacar', 'Tijera Jaguar Pre Style Relax Entresacar 28 Dientes 5.5 Pulgadas', 'tijera-jaguar-pre-style-relax-entresacar-28d', 'JAG-ENT-28D', 'Tijera de pulir y entresacar de 28 dientes microdentados prismáticos fabricada en acero templado en hielo en Solingen, Alemania.', 'La tijera de pulir por excelencia en peluquerías y barberías profesionales. Forjada con acero inoxidable especial de Solingen y sometida a tratamiento criogénico Friodur (-180 °C) que multiplica la dureza y longevidad del filo. Sus 28 dientes con microdentado en forma de prisma sujetan el pelo con precisión impidiendo que se desplace, logrando transiciones de volumen impecables.', '{"_id":"cat-tijeras","title":"Tijeras, Navajas & Filos","slug":"tijeras-filos-profesionales","description":"Tijeras de corte microdentadas, filo dulce Solingen, navajas de barbero y hojas de afeitar profesionales.","icon":"Sparkles","image":"/uploads/articulos/treet-platinum-100-pack.jpeg"}'::jsonb, '{"_id":"b-jaguar","name":"Jaguar Solingen","slug":"jaguar"}'::jsonb, '["/uploads/articulos/navajas-barber-custom.jpeg"]'::jsonb, 'Estuche blíster oficial Jaguar Solingen Germany con llave de regulación Vario', '[{"key":"Origen","value":"Solingen, Alemania (original auténtico grabado en hoja)"},{"key":"Medida","value":"5.5 pulgadas (14 cm)"},{"key":"Dientes","value":"28 dientes prismáticos con microdentado de retención"},{"key":"Mango","value":"Diseño Offset ergonómico para relajar la tensión de hombro y muñeca"},{"key":"Tornillo","value":"Vario Screw regulable con moneda o llave"},{"key":"Acabado","value":"Acero inoxidable satinado mate antirreflejos"}]'::jsonb, TRUE, TRUE, FALSE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-jaguar-filo-dulce', 'Tijera Jaguar Pre Style Ergo Filo Dulce Profesional 5.5 Pulgadas', 'tijera-jaguar-pre-style-ergo-filo-dulce-55', 'JAG-FD-55', 'Tijera de corte recto con filo dulce (''honing'') pulido a espejo para cortes limpios, despuntes y técnicas de desfilado continuo.', 'Máxima precisión alemana en tus manos. La Jaguar Pre Style Ergo Filo Dulce ofrece un deslizamiento suave y un corte contundente de punta a talón. El filo dulce pulido a espejo permite realizar cortes rectos perfectos y deslizarse suavemente en técnicas de desfilado y ''slide cutting'' sin masticar la fibra capilar.', '{"_id":"cat-tijeras","title":"Tijeras, Navajas & Filos","slug":"tijeras-filos-profesionales","description":"Tijeras de corte microdentadas, filo dulce Solingen, navajas de barbero y hojas de afeitar profesionales.","icon":"Sparkles","image":"/uploads/articulos/treet-platinum-100-pack.jpeg"}'::jsonb, '{"_id":"b-jaguar","name":"Jaguar Solingen","slug":"jaguar"}'::jsonb, '["/uploads/articulos/navajas-barber-custom.jpeg"]'::jsonb, 'Estuche oficial Jaguar Solingen con llave Vario y anillos reductores de dedo', '[{"key":"Origen","value":"Solingen, Alemania (auténtica garantía alemana)"},{"key":"Medida","value":"5.5 pulgadas (14 cm)"},{"key":"Filo","value":"Filo Dulce (Honed Blade) pulido de alta retención"},{"key":"Forma","value":"Clásica Ergo con apoyadedo desmontable"},{"key":"Material","value":"Acero inoxidable alemán con tratamiento térmico Friodur"},{"key":"Regulación","value":"Tornillo Vario para ajuste milimétrico de tensión"}]'::jsonb, TRUE, TRUE, FALSE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-kemei-km2600', 'Máquina de Corte Kemei KM-2600 Cordless Precision Fade Clipper', 'maquina-corte-kemei-km2600-cordless', 'KMI-KM2600', 'Clipper inalámbrica con potente motor silencioso de 6.000 RPM, palanca de graduación metálica y batería de 2.200 mAh.', 'La Kemei KM-2600 es famosa entre barberos de todo el mundo por ofrecer un rendimiento y una ergonomía inspirados en los modelos de gama alta a una fracción del costo. Su motor rotativo de 6.000 RPM trabaja con suavidad y bajo nivel de vibración, mientras que su cuchilla de acero inoxidable cromada garantiza cortes nítidos y degradados prolijos.', '{"_id":"cat-maquinas","title":"Máquinas de Corte & Trimmers","slug":"maquinas-corte-trimmers","description":"Clippers inalámbricas, trimmers de terminación, shavers de lámina y kits profesionales de marcas líderes.","icon":"Scissors","image":"/uploads/articulos/wahl-senior-cordless.jpeg"}'::jsonb, '{"_id":"b-kemei","name":"Kemei Professional","slug":"kemei"}'::jsonb, '["/uploads/articulos/kemei-km2600-clipper.jpeg"]'::jsonb, 'Caja completa con máquina, 4 peines guía (3, 6, 10, 13 mm), cargador, aceite y peine', '[{"key":"Motor","value":"Rotativo de 6.000 RPM con reducción acústica"},{"key":"Cuchilla","value":"Acero inoxidable templado cromado"},{"key":"Batería","value":"Iones de litio de 2.200 mAh (120 minutos de uso)"},{"key":"Palanca de ajuste","value":"Regulable para desvanecidos suaves"},{"key":"Tiempo de carga","value":"180 minutos para recarga total"},{"key":"Peines guía","value":"4 medidas estándar incluidas (3, 6, 10, 13 mm)"}]'::jsonb, TRUE, FALSE, FALSE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-patillera-kemei2299', 'Trimmer Kemei KM-2299 Professional Hair Clipper / Trimmer', 'trimmer-patillera-kemei-km2299', 'KMI-KM2299', 'Patillera de terminación con cuchilla T-Blade Black DLC, corte ultra al ras de 0.1 mm y potente motor de 7.500 RPM.', 'Considerada una de las trimmers más veloces y precisas de su categoría. La Kemei KM-2299 monta una cuchilla en T recubierta en DLC negro que no pellizca la piel y corta a 0.1 mm con facilidad. Su motor acelerado a 7.500 RPM asegura pasadas firmes en contornos de barba, nuca y líneas definidas sin atascos.', '{"_id":"cat-maquinas","title":"Máquinas de Corte & Trimmers","slug":"maquinas-corte-trimmers","description":"Clippers inalámbricas, trimmers de terminación, shavers de lámina y kits profesionales de marcas líderes.","icon":"Scissors","image":"/uploads/articulos/wahl-senior-cordless.jpeg"}'::jsonb, '{"_id":"b-kemei","name":"Kemei Professional","slug":"kemei"}'::jsonb, '["/uploads/articulos/kemei-km2299-clipper.jpeg","/uploads/articulos/kemei-km2299-clipper-2.jpeg"]'::jsonb, 'Caja con trimmer, 3 peines guía (1, 2, 3 mm), cable de carga USB y lubricante', '[{"key":"Motor","value":"Alta velocidad de 7.500 RPM de par constante"},{"key":"Cuchilla","value":"T-Blade expuesta de acero con recubrimiento Black DLC"},{"key":"Corte mínimo","value":"0.1 mm (zero-gap real para delineados)"},{"key":"Batería","value":"Litio de 1.200 mAh (hasta 180 minutos de autonomía)"},{"key":"Carga","value":"USB Tipo-C universal de carga rápida"},{"key":"Peso","value":"Ultraligera, solo 180 gramos para agilidad absoluta"}]'::jsonb, TRUE, TRUE, FALSE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-filo-treet-premium', 'Hojas de Afeitar Treet Platinum Super Stainless (Pack x 200)', 'hojas-afeitar-treet-platinum-pack-200', 'TRT-PLT-200', 'Hojas de afeitar dobles Treet Platinum de calidad premium con triple recubrimiento de platino, cromo y PTFE.', 'Pack económico de alta demanda para salones de barbería con alto volumen diario de afeitados. Cada filo Treet Platinum es fabricado bajo normas de precisión con acero inoxidable de grado quirúrgico y recubierto con micropartículas de Platino para prolongar la nitidez del corte y minimizar la irritación dérmica.', '{"_id":"cat-tijeras","title":"Tijeras, Navajas & Filos","slug":"tijeras-filos-profesionales","description":"Tijeras de corte microdentadas, filo dulce Solingen, navajas de barbero y hojas de afeitar profesionales.","icon":"Sparkles","image":"/uploads/articulos/treet-platinum-100-pack.jpeg"}'::jsonb, '{"_id":"b-treet","name":"Treet Corporation","slug":"treet"}'::jsonb, '["/uploads/articulos/treet-platinum-200-blades.jpeg","/uploads/articulos/treet-platinum-100-pack.jpeg"]'::jsonb, 'Pack comercial con 20 cajitas x 10 filos (200 hojas dobles)', '[{"key":"Contenido","value":"200 hojas dobles (equivale a 400 filos de uso en navaja partida)"},{"key":"Presentación","value":"20 estuches individuales de 10 unidades cada uno"},{"key":"Material","value":"Acero inoxidable templado de alta resistencia"},{"key":"Recubrimiento","value":"Triple capa Platinum, Chromium y PTFE"},{"key":"Envoltorio","value":"Doble papel parafinado individual por hoja"},{"key":"Rendimiento","value":"Suavidad extrema y corte limpio sin tirones"}]'::jsonb, TRUE, FALSE, FALSE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-capas-wmark', 'Capa de Barbería WMARK Professional Impermeable y Antiestática', 'capa-barberia-wmark-impermeable-antiestatica', 'WMK-CAP-01', 'Capa de corte extra grande de 140 x 160 cm en poliéster impermeable con tratamiento antiestático y broches metálicos.', 'Confeccionada en tela de poliéster sedoso de alta densidad que repele los cabellos cortados impidiendo que se claven en el tejido. Su tratamiento impermeable protege la ropa del cliente contra salpicaduras de agua, tinturas y lociones. Cuenta con cuello elástico de ajuste universal con broches metálicos inoxidables de múltiples posiciones.', '{"_id":"cat-accesorios","title":"Accesorios, Capas & Barbería","slug":"accesorios-capas-barberia","description":"Capas WMARK, peines de corte, alzas premium, papel de cuello, rociadores y cosmética profesional.","icon":"Package","image":"/uploads/articulos/capa-wmark-negra.jpeg"}'::jsonb, '{"_id":"b-wmark","name":"WMARK Professional","slug":"wmark"}'::jsonb, '["/uploads/articulos/capa-wmark-negra.jpeg","/uploads/articulos/capa-wmark-negra-2.jpeg","/uploads/articulos/capa-wmark-blanca.jpeg"]'::jsonb, 'Bolsa individual hermética con capa serigrafiada WMARK', '[{"key":"Dimensiones","value":"140 cm de ancho x 160 cm de largo (cobertura total de cliente)"},{"key":"Material","value":"100% poliéster sedoso antiestático e impermeable"},{"key":"Cierre del cuello","value":"Cuello elástico ajustable con broches metálicos niquelados"},{"key":"Diseño","value":"Variante Negra clásica o Blanca Barber con logo WMARK"},{"key":"Limpieza","value":"Lavable a máquina, secado ultra rápido"}]'::jsonb, TRUE, TRUE, FALSE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-papel-cuello-look-pack5', 'Papel Cuello Elástico Autoadhesivo Luke Paper Professional (Pack x 5 Rollos)', 'papel-cuello-elastico-luke-paper-pack-5-rollos', 'LUK-NCK-100', 'Rollos de papel de cuello higiénico elástico con tira autoadhesiva médica que previene el ingreso de pelos en la ropa.', 'La norma de higiene básica en cualquier servicio de barbería y salón. El papel de cuello Luke Paper está elaborado con celulosa pura micro-gofrada con elasticidad de hasta un 200%, adaptándose suavemente al contorno del cuello de cualquier cliente sin ahogar. Su tira de goma autoadhesiva azul sella al contacto impidiendo que los pelos cortados se filtren hacia el cuello de la camisa.', '{"_id":"cat-accesorios","title":"Accesorios, Capas & Barbería","slug":"accesorios-capas-barberia","description":"Capas WMARK, peines de corte, alzas premium, papel de cuello, rociadores y cosmética profesional.","icon":"Package","image":"/uploads/articulos/capa-wmark-negra.jpeg"}'::jsonb, '{"_id":"b-luke","name":"Luke Paper","slug":"luke"}'::jsonb, '["/uploads/articulos/luke-paper-cuello.jpeg"]'::jsonb, 'Pack termosellado con 5 rollos (500 tiras en total)', '[{"key":"Cantidad","value":"5 rollos de 100 tiras precortadas cada uno (500 servicios)"},{"key":"Elasticidad","value":"Hasta 200% de elongación sin romperse"},{"key":"Adhesión","value":"Pegamento médico hipoalergénico sensible a la presión"},{"key":"Material","value":"Celulosa virgen absorbente de sudor y humedad"},{"key":"Higiene","value":"100% descartable de uso único por cliente"}]'::jsonb, TRUE, FALSE, FALSE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-papel-suelto-individual', 'Papel de Cuello Elástico Barber Rollo Suelto Individual (100 Tiras)', 'papel-cuello-rollo-suelto-individual-100-tiras', 'LUK-NCK-01', 'Rollo individual de papel de cuello elástico autoadhesivo para reposición ágil en dispensadores de estación.', 'Formato fraccionado por unidad para profesionales independientes o para reponer dispensadores de mesa de corte. Ofrece la misma calidad de celulosa elástica y adhesivo hipoalergénico que el pack por 5, listo para colocar en cualquier dispensador circular de acrílico o plástico.', '{"_id":"cat-accesorios","title":"Accesorios, Capas & Barbería","slug":"accesorios-capas-barberia","description":"Capas WMARK, peines de corte, alzas premium, papel de cuello, rociadores y cosmética profesional.","icon":"Package","image":"/uploads/articulos/capa-wmark-negra.jpeg"}'::jsonb, '{"_id":"b-luke","name":"Luke Paper","slug":"luke"}'::jsonb, '["/uploads/articulos/luke-paper-cuello.jpeg"]'::jsonb, 'Rollo individual suelto con 100 tiras precortadas', '[{"key":"Contenido","value":"1 rollo individual con 100 tiras precortadas"},{"key":"Ancho de tira","value":"6.5 cm de protección en cuello"},{"key":"Adhesivo","value":"Banda autoadhesiva azul de fijación instantánea"},{"key":"Compatibilidad","value":"Calce estándar para dispensadores de cuello acrílicos"},{"key":"Propiedad","value":"Elástico, absorbente y suave con la piel"}]'::jsonb, TRUE, FALSE, FALSE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-filos-treet-100', 'Hojas de Afeitar Treet Platinum Super Stainless (Caja x 100 Filos)', 'hojas-afeitar-treet-platinum-caja-100', 'TRT-PLT-100', 'Caja clásica de 100 hojas dobles Treet Platinum de acero inoxidable con filo de altísima suavidad y precisión.', 'La caja tradicional de 100 hojas de afeitar dobles Treet Platinum. Reconocida por su filo dulce de corte progresivo que no raspa ni tira de la raíz. Cada hoja viene protegida en doble envoltura de papel encerado para mantener la lubricación de fábrica y evitar la humedad hasta el momento exacto de su uso en el salón.', '{"_id":"cat-tijeras","title":"Tijeras, Navajas & Filos","slug":"tijeras-filos-profesionales","description":"Tijeras de corte microdentadas, filo dulce Solingen, navajas de barbero y hojas de afeitar profesionales.","icon":"Sparkles","image":"/uploads/articulos/treet-platinum-100-pack.jpeg"}'::jsonb, '{"_id":"b-treet","name":"Treet Corporation","slug":"treet"}'::jsonb, '["/uploads/articulos/treet-platinum-100-pack.jpeg","/uploads/articulos/treet-platinum-100-londres.jpeg"]'::jsonb, 'Caja dispensadora con 10 cajitas de 10 filos dobles (100 hojas / 200 usos)', '[{"key":"Contenido","value":"100 hojas dobles descartables (200 filos de navaja)"},{"key":"Presentación","value":"Caja con 10 dispensadores de 10 unidades cada uno"},{"key":"Material","value":"Acero inoxidable sueco templado al vacío"},{"key":"Filo","value":"Recubierto en Platino y Polímero PTFE antifricción"},{"key":"Seguridad","value":"Papel encerado individual grado hospitalario"}]'::jsonb, TRUE, TRUE, FALSE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-wmark-ng8634-kit', 'Kit Barbería WMARK NG-8634 Panther Edition (Clipper + Trimmer)', 'kit-barberia-wmark-ng8634-panther-combo', 'WMK-NG8634-KIT', 'Combo completo de corte y terminación con estación de carga dual simultánea, motores rotativos rápidos y diseño ergonómico Panther.', 'La solución integral para equipar o renovar la estación de corte con estética uniforme y máxima potencia. El combo WMARK NG-8634 incluye una máquina de corte (Clipper) con motor de 6.500 RPM y palanca de ajuste, más una patillera (Trimmer) a 7.000 RPM con cuchilla en T expuesta. Ambas descansan y se recargan al mismo tiempo sobre una base de carga dual de un solo enchufe.', '{"_id":"cat-maquinas","title":"Máquinas de Corte & Trimmers","slug":"maquinas-corte-trimmers","description":"Clippers inalámbricas, trimmers de terminación, shavers de lámina y kits profesionales de marcas líderes.","icon":"Scissors","image":"/uploads/articulos/wahl-senior-cordless.jpeg"}'::jsonb, '{"_id":"b-wmark","name":"WMARK Professional","slug":"wmark"}'::jsonb, '["/uploads/articulos/wmark-ng8634-barber-kit.jpeg"]'::jsonb, 'Caja combo de presentación con Clipper + Trimmer, base de carga dual, peines guía y accesorios', '[{"key":"Clipper","value":"Motor rotativo 6.500 RPM, cuchilla fade ajustable, batería 2.500 mAh (240 min)"},{"key":"Trimmer","value":"Motor rápido 7.000 RPM, T-blade de 0.1 mm, batería 2.000 mAh (180 min)"},{"key":"Base de carga","value":"Estación dual con LEDs indicadores de carga independientes"},{"key":"Accesorios incluidos","value":"6 alzas magnéticas para clipper, 3 alzas para trimmer, cable y aceite"},{"key":"Carcasa","value":"Polímero mate Panther Black con insertos metálicos"}]'::jsonb, TRUE, TRUE, TRUE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-cuchilla-wahl-ceramica', 'Cuchillas Cerámicas Móviles Fade para Máquinas Wahl (Camufladas y Blancas)', 'cuchilla-ceramica-movil-fade-para-wahl', 'CCH-CER-CAMO', 'Cuchilla móvil de cerámica de zirconio para máquinas Wahl, disipa un 75% más de calor y no pierde el filo.', 'Reemplazo directo para la cuchilla móvil metálica de máquinas tipo Wahl. La cerámica de zirconio de grado aeroespacial disipa la temperatura por fricción hasta un 75% más rápido que el acero tradicional, manteniendo la máquina fría incluso tras horas de corte continuo. Además, al no oxidarse ni desgastarse por roce, conserva el filo nítido hasta 5 veces más tiempo.', '{"_id":"cat-accesorios","title":"Accesorios, Capas & Barbería","slug":"accesorios-capas-barberia","description":"Capas WMARK, peines de corte, alzas premium, papel de cuello, rociadores y cosmética profesional.","icon":"Package","image":"/uploads/articulos/capa-wmark-negra.jpeg"}'::jsonb, '{"_id":"b-londress","name":"Londress Series","slug":"londress-pro"}'::jsonb, '["/uploads/articulos/cuchilla-ceramica-azul-camo.jpeg","/uploads/articulos/cuchilla-ceramica-roja-camo.jpeg","/uploads/articulos/cuchilla-ceramica-verde-camo.jpeg"]'::jsonb, 'Blíster sellado con cuchilla móvil cerámica de alta resistencia', '[{"key":"Material","value":"Cerámica avanzada de óxido de Zirconio (ZrO2) de alta densidad"},{"key":"Temperatura","value":"Reduce el calor de contacto hasta un 75% comparado al acero"},{"key":"Compatibilidad","value":"Wahl Magic Clip Cordless, Wahl Senior Cordless, Super Taper, Legend y clones"},{"key":"Dientes","value":"Perfil Fade Stagger-Tooth de corte ultra nítido"},{"key":"Diseño","value":"Disponibles en acabado Camuflado (Azul, Rojo, Verde) y Blanco Cerámico"}]'::jsonb, TRUE, TRUE, FALSE) ON CONFLICT (_id) DO NOTHING;
