-- ====================================================================
-- DISTRIBUIDORA LONDRESS - ESQUEMA Y DATOS INICIALES PARA SUPABASE (POSTGRESQL)
-- ====================================================================
-- INSTRUCCIONES:
-- 1. En tu proyecto de Supabase (https://supabase.com), ve a "SQL Editor".
-- 2. Copia y pega TODO este archivo y haz clic en "Run" (Ejecutar).
-- 3. ¡Listo! Todas las tablas, permisos y tus 28 productos reales quedarán creados.
-- ====================================================================

-- 1. TABLA DE CONSULTAS DE CONTACTO (INQUIRIES)
CREATE TABLE IF NOT EXISTS inquiries (
  _id TEXT PRIMARY KEY,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "businessName" TEXT,
  "contactPerson" TEXT NOT NULL,
  phone TEXT NOT NULL,
  city TEXT,
  "businessType" TEXT,
  message TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending'
);

-- 2. TABLA DE PRODUCTOS
CREATE TABLE IF NOT EXISTS products (
  _id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  sku TEXT,
  "shortDescription" TEXT,
  description TEXT,
  category JSONB,
  brand JSONB,
  images JSONB,
  presentation TEXT,
  specifications JSONB,
  "inStock" BOOLEAN DEFAULT TRUE,
  featured BOOLEAN DEFAULT FALSE,
  "isNew" BOOLEAN DEFAULT FALSE
);

-- 3. TABLA DE CATEGORÍAS
CREATE TABLE IF NOT EXISTS categories (
  _id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  description TEXT,
  image TEXT,
  "itemCount" INTEGER DEFAULT 0
);

-- 4. TABLA DE MARCAS
CREATE TABLE IF NOT EXISTS brands (
  _id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  logo TEXT
);

-- 5. TABLA DE CONFIGURACIÓN DEL SITIO
CREATE TABLE IF NOT EXISTS site_settings (
  id TEXT PRIMARY KEY DEFAULT 'default',
  data JSONB NOT NULL
);

-- HABILITAR ROW LEVEL SECURITY (RLS) Y PERMISOS ABIERTOS
ALTER TABLE inquiries ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE brands ENABLE ROW LEVEL SECURITY;
ALTER TABLE site_settings ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
  DROP POLICY IF EXISTS "Public access to inquiries" ON inquiries;
  CREATE POLICY "Public access to inquiries" ON inquiries FOR ALL USING (true) WITH CHECK (true);

  DROP POLICY IF EXISTS "Public access to products" ON products;
  CREATE POLICY "Public access to products" ON products FOR ALL USING (true) WITH CHECK (true);

  DROP POLICY IF EXISTS "Public access to categories" ON categories;
  CREATE POLICY "Public access to categories" ON categories FOR ALL USING (true) WITH CHECK (true);

  DROP POLICY IF EXISTS "Public access to brands" ON brands;
  CREATE POLICY "Public access to brands" ON brands FOR ALL USING (true) WITH CHECK (true);

  DROP POLICY IF EXISTS "Public access to site_settings" ON site_settings;
  CREATE POLICY "Public access to site_settings" ON site_settings FOR ALL USING (true) WITH CHECK (true);
END $$;

-- 6. CARGA DE CONFIGURACIÓN INICIAL
INSERT INTO site_settings (id, data) 
VALUES ('default', '{"companyName":"Distribuidora Londress","slogan":"Distribución mayorista de insumos de peluquería, barbería, máquinas de corte y equipamiento profesional","whatsapp":"5491123456789","phone":"+54 11 4567-8900","email":"ventas@distribuidoralondress.com","address":"Av. Corrientes 3820, Distrito Comercial","city":"Buenos Aires, Argentina","schedule":"Lunes a Viernes de 08:30 a 18:00 hs | Sábados de 09:00 a 13:00 hs","heroTitle":"Insumos de Peluquería, Barbería y Máquinas Profesionales","heroSubtitle":"Abastecimiento integral para salones de belleza, barberías, academias y distribuidores. Herramientas de precisión, repuestos originales, cosmética capilar y servicio técnico garantizado.","heroBadge":"Distribuidor Oficial Barber & Hair Salon"}'::jsonb)
ON CONFLICT (id) DO UPDATE SET data = EXCLUDED.data;

-- 7. CARGA DE CATEGORÍAS
INSERT INTO categories (_id, title, slug, description, image, "itemCount") VALUES ('cat-maquinas', 'Máquinas de Corte & Trimmers', 'maquinas-corte-trimmers', 'Clippers inalámbricas, trimmers de terminación, shavers de lámina y kits profesionales de marcas líderes.', '/uploads/articulos/wahl-senior-cordless.jpeg', 12) ON CONFLICT (_id) DO NOTHING;
INSERT INTO categories (_id, title, slug, description, image, "itemCount") VALUES ('cat-tijeras', 'Tijeras, Navajas & Filos', 'tijeras-filos-profesionales', 'Tijeras de corte microdentadas, filo dulce japonés, navajas de barbero y hojas de afeitar Treet Platinum.', '/uploads/articulos/treet-platinum-100-pack.jpeg', 4) ON CONFLICT (_id) DO NOTHING;
INSERT INTO categories (_id, title, slug, description, image, "itemCount") VALUES ('cat-secadores', 'Secadores & Herramientas Térmicas', 'secadores-herramientas-termicas', 'Secadores de alto rendimiento con motor italiano, planchas alisadoras de titanio cerámico y bucleadoras.', '/uploads/articulos/secador-tucano-8600w.jpeg', 1) ON CONFLICT (_id) DO NOTHING;
INSERT INTO categories (_id, title, slug, description, image, "itemCount") VALUES ('cat-accesorios', 'Accesorios, Capas & Barbería', 'accesorios-capas-barberia', 'Capas WMARK, peines de carbono, papel de cuello Luke Paper, rociadores, aerosoles Andis Cool Care y lubricantes.', '/uploads/articulos/capa-wmark-negra.jpeg', 11) ON CONFLICT (_id) DO NOTHING;

-- 8. CARGA DE MARCAS
INSERT INTO brands (_id, name, slug, logo) VALUES ('b-londress', 'Londress Pro Series', 'londress-pro', NULL) ON CONFLICT (_id) DO NOTHING;
INSERT INTO brands (_id, name, slug, logo) VALUES ('b-wahl', 'Wahl Professional', 'wahl', NULL) ON CONFLICT (_id) DO NOTHING;
INSERT INTO brands (_id, name, slug, logo) VALUES ('b-babyliss', 'BaBylissPRO', 'babyliss-pro', NULL) ON CONFLICT (_id) DO NOTHING;
INSERT INTO brands (_id, name, slug, logo) VALUES ('b-vgr', 'VGR Professional', 'vgr', NULL) ON CONFLICT (_id) DO NOTHING;
INSERT INTO brands (_id, name, slug, logo) VALUES ('b-wmark', 'WMARK Professional', 'wmark', NULL) ON CONFLICT (_id) DO NOTHING;
INSERT INTO brands (_id, name, slug, logo) VALUES ('b-kemei', 'Kemei Professional', 'kemei', NULL) ON CONFLICT (_id) DO NOTHING;
INSERT INTO brands (_id, name, slug, logo) VALUES ('b-andis', 'Andis USA', 'andis', NULL) ON CONFLICT (_id) DO NOTHING;
INSERT INTO brands (_id, name, slug, logo) VALUES ('b-treet', 'Treet Platinum', 'treet', NULL) ON CONFLICT (_id) DO NOTHING;
INSERT INTO brands (_id, name, slug, logo) VALUES ('b-tucano', 'Tucano Hair Tools', 'tucano', NULL) ON CONFLICT (_id) DO NOTHING;
INSERT INTO brands (_id, name, slug, logo) VALUES ('b-dompelo', 'Dom Pelo', 'dom-pelo', NULL) ON CONFLICT (_id) DO NOTHING;
INSERT INTO brands (_id, name, slug, logo) VALUES ('b-l3vel3', 'L3VEL3', 'l3vel3', NULL) ON CONFLICT (_id) DO NOTHING;
INSERT INTO brands (_id, name, slug, logo) VALUES ('b-infinity', 'Infinity Look''s Hair', 'infinity', NULL) ON CONFLICT (_id) DO NOTHING;

-- 9. CARGA DE PRODUCTOS REALES (28 ARTÍCULOS)
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-wahl-senior', 'Máquina Wahl Professional 5-Star Cordless Senior Metal Case', 'wahl-5-star-cordless-senior-metal-case', 'WHL-SNR-01', 'Carcasa metálica ergonómica de alta resistencia, motor V9000 de torque constante y batería de iones de litio.', 'La Wahl Cordless Senior es el estándar indiscutido para barberos exigentes. Equipada con carcasa de aluminio de servicio pesado para máximo control y estabilidad, motor rotativo que no decae en cabellos densos y palanca de ajuste metálica con graduación milimétrica (0.8mm a 2.5mm). Cuchilla ajustable a cero espacio para desvanecimientos ultra limpios.', '{"_id":"cat-maquinas","title":"Máquinas de Corte & Trimmers","slug":"maquinas-corte-trimmers","description":"Clippers inalámbricas, trimmers de terminación, shavers de lámina y kits profesionales de marcas líderes.","icon":"Scissors","image":"/uploads/articulos/wahl-senior-cordless.jpeg","itemCount":12}'::jsonb, '{"_id":"b-wahl","name":"Wahl Professional","slug":"wahl"}'::jsonb, '["/uploads/articulos/wahl-senior-cordless.jpeg","/uploads/articulos/wahl-senior-cordless-2.jpeg"]'::jsonb, 'Caja individual cerrada oficial (Consulte precio por bulto)', '[{"key":"Motor","value":"Rotativo V9000 de alta torsión"},{"key":"Carcasa","value":"Aluminio Heavy Duty Metal Case"},{"key":"Autonomía","value":"Batería Litio 80 minutos continuos"},{"key":"Regulación","value":"Palanca metálica 0.8 mm - 2.5 mm"},{"key":"Garantía","value":"Oficial Wahl Professional 2 años"}]'::jsonb, TRUE, TRUE, TRUE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-wahl-magic-clip-bg', 'Máquina Wahl 5-Star Cordless Magic Clip Black & Gold Edition', 'wahl-5-star-magic-clip-black-gold', 'WHL-MGC-BG', 'Edición exclusiva Black & Gold con cuchilla Stagger-Tooth bañada en oro y motor de alta velocidad optimizado.', 'La máquina de corte más aclamada del mundo en su versión dorada premium. La cuchilla patentada Stagger-Tooth emite el característico sonido ''Crunch'' que guía al barbero para un difuminado perfecto sin líneas marcadas. Batería de iones de litio de más de 100 minutos de uso ininterrumpido.', '{"_id":"cat-maquinas","title":"Máquinas de Corte & Trimmers","slug":"maquinas-corte-trimmers","description":"Clippers inalámbricas, trimmers de terminación, shavers de lámina y kits profesionales de marcas líderes.","icon":"Scissors","image":"/uploads/articulos/wahl-senior-cordless.jpeg","itemCount":12}'::jsonb, '{"_id":"b-wahl","name":"Wahl Professional","slug":"wahl"}'::jsonb, '["/uploads/articulos/wahl-magic-clip-black-gold.jpeg","/uploads/articulos/wahl-magic-clip-black-gold-2.jpeg"]'::jsonb, 'Caja individual oficial con 8 peines guía premium', '[{"key":"Cuchilla","value":"Stagger-Tooth bañada en Titanio Oro"},{"key":"Motor","value":"Rotativo High-Speed mejorado"},{"key":"Autonomía","value":"Más de 100 minutos de trabajo"},{"key":"Peso","value":"290g ultraliviana y balanceada"}]'::jsonb, TRUE, TRUE, TRUE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-babyliss-fxone-black', 'Trimmer BaBylissPRO FXONE All-Metal Li-ion Black Edition', 'babylisspro-fxone-all-metal-trimmer-black', 'BBY-FXONE-BLK', 'Nuevo sistema FXONE con batería universal intercambiable en un clic, motor brushless y cuerpo moleteado.', 'La cúspide de la ingeniería para terminaciones de barbería. Sistema modular que permite retirar y reemplazar la batería en un segundo. Chasis metálico estriado negro mate que garantiza agarre óptimo aún con manos húmedas. Cuchilla en T de titanio con visión 360° para líneas nítidas.', '{"_id":"cat-maquinas","title":"Máquinas de Corte & Trimmers","slug":"maquinas-corte-trimmers","description":"Clippers inalámbricas, trimmers de terminación, shavers de lámina y kits profesionales de marcas líderes.","icon":"Scissors","image":"/uploads/articulos/wahl-senior-cordless.jpeg","itemCount":12}'::jsonb, '{"_id":"b-babyliss","name":"BaBylissPRO","slug":"babyliss-pro"}'::jsonb, '["/uploads/articulos/babylisspro-fxone-black.jpeg"]'::jsonb, 'Caja con base de carga y batería modular FXONE', '[{"key":"Sistema","value":"FXONE Batería recambiable universal"},{"key":"Motor","value":"Digital sin escobillas (Brushless) N1"},{"key":"Cuchilla","value":"T-Blade DLC/Titanio expuesta 360°"},{"key":"Carcasa","value":"Aluminio moleteado anti-deslizante"}]'::jsonb, TRUE, TRUE, TRUE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-babyliss-fxone-gold', 'Trimmer BaBylissPRO FXONE All-Metal Li-ion Gold Edition', 'babylisspro-fxone-all-metal-trimmer-gold', 'BBY-FXONE-GLD', 'Edición Gold Luxury con acabado dorado brillante, motor Ferrari brushless y batería intercambiable FXONE.', 'Máxima prestancia y potencia inigualable. Creada para barberías de alta gama que exigen precisión milimétrica en dibujos, afeitados en seco y líneas de contorno. Su motor digital entrega 7.200 RPM constantes sin calentamiento.', '{"_id":"cat-maquinas","title":"Máquinas de Corte & Trimmers","slug":"maquinas-corte-trimmers","description":"Clippers inalámbricas, trimmers de terminación, shavers de lámina y kits profesionales de marcas líderes.","icon":"Scissors","image":"/uploads/articulos/wahl-senior-cordless.jpeg","itemCount":12}'::jsonb, '{"_id":"b-babyliss","name":"BaBylissPRO","slug":"babyliss-pro"}'::jsonb, '["/uploads/articulos/babylisspro-fxone-gold.jpeg"]'::jsonb, 'Caja de lujo con base de carga dorada y batería FXONE', '[{"key":"Acabado","value":"Dorado espejo Luxury Gold"},{"key":"Velocidad","value":"7.200 RPM de par constante"},{"key":"Batería","value":"FXONE Lithium-Ion intercambiable"},{"key":"Cuchilla","value":"Titanio Oro Deep-Tooth ajustable a cero"}]'::jsonb, TRUE, TRUE, TRUE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-vgr-v011', 'Máquina de Corte VGR Navigator V-011 Professional Clipper', 'vgr-navigator-v011-professional-hair-clipper', 'VGR-V011', 'Clipper profesional con batería de 2200 mAh, cuchillas de acero amigables con la piel y palanca taper.', 'La mejor relación precio-calidad del mercado mayorista. Diseñada para trabajo diario en salones, posee batería de litio de alta densidad que rinde hasta 180 minutos de uso, cuerpo bicolor resistente y micro-palanca lateral de ajuste de altura.', '{"_id":"cat-maquinas","title":"Máquinas de Corte & Trimmers","slug":"maquinas-corte-trimmers","description":"Clippers inalámbricas, trimmers de terminación, shavers de lámina y kits profesionales de marcas líderes.","icon":"Scissors","image":"/uploads/articulos/wahl-senior-cordless.jpeg","itemCount":12}'::jsonb, '{"_id":"b-vgr","name":"VGR Professional","slug":"vgr"}'::jsonb, '["/uploads/articulos/vgr-v011-clipper.jpeg","/uploads/articulos/vgr-v011-clipper-2.jpeg","/uploads/articulos/vgr-v011-clipper-3.jpeg"]'::jsonb, 'Caja individual con 4 peines guía + aceite + cepillo (Venta por unidad y bulto)', '[{"key":"Batería","value":"2200 mAh Litio (180 min autonomía)"},{"key":"Cuchillas","value":"Acero quirúrgico Skin-friendly"},{"key":"Palanca","value":"Multi-cut Taper Lever"},{"key":"Carga","value":"USB universal con indicador LED"}]'::jsonb, TRUE, FALSE, FALSE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-vgr-v275-gold', 'Trimmer VGR Voyager V-275 Professional Hair Trimmer Gold', 'vgr-voyager-v275-professional-hair-trimmer-gold', 'VGR-V275', 'Trimmer metálica dorada texturada con display digital de carga/RPM y cuchilla T-Blade de terminación.', 'Cuerpo completamente metálico con grabado antideslizante. Pantalla digital que informa el porcentaje exacto de batería y velocidad de trabajo. Especialmente calibrada para rebajes de barba, cuello y detalles finos.', '{"_id":"cat-maquinas","title":"Máquinas de Corte & Trimmers","slug":"maquinas-corte-trimmers","description":"Clippers inalámbricas, trimmers de terminación, shavers de lámina y kits profesionales de marcas líderes.","icon":"Scissors","image":"/uploads/articulos/wahl-senior-cordless.jpeg","itemCount":12}'::jsonb, '{"_id":"b-vgr","name":"VGR Professional","slug":"vgr"}'::jsonb, '["/uploads/articulos/vgr-v275-trimmer-gold.jpeg"]'::jsonb, 'Caja de presentación con peines guía de 1, 2 y 3 mm', '[{"key":"Cuerpo","value":"Metálico dorado labrado"},{"key":"Display","value":"LED digital inteligente"},{"key":"Batería","value":"1500 mAh Litio alta duración"},{"key":"Cuchilla","value":"T-Blade acero inoxidable"}]'::jsonb, TRUE, FALSE, TRUE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-vgr-v938-afa', 'Trimmer Corporal VGR V-938 Edición Oficial AFA Selección Argentina', 'vgr-v938-body-trimmer-afa-seleccion-argentina', 'VGR-V938-AFA', 'Recortadora corporal y de detalles con cuchilla cerámica anti-pellizcos, resistencia IPX7 al agua y base de apoyo.', 'Producto oficial licenciado de la Asociación del Fútbol Argentino (AFA). Cuchilla cerámica con bordes redondeados que no irrita zonas sensibles. 100% impermeable con certificación IPX7 para uso en seco o bajo el agua.', '{"_id":"cat-maquinas","title":"Máquinas de Corte & Trimmers","slug":"maquinas-corte-trimmers","description":"Clippers inalámbricas, trimmers de terminación, shavers de lámina y kits profesionales de marcas líderes.","icon":"Scissors","image":"/uploads/articulos/wahl-senior-cordless.jpeg","itemCount":12}'::jsonb, '{"_id":"b-vgr","name":"VGR Professional","slug":"vgr"}'::jsonb, '["/uploads/articulos/vgr-v938-afa-trimmer.jpeg"]'::jsonb, 'Caja con licencia oficial AFA con base cargadora vertical', '[{"key":"Licencia","value":"Oficial AFA (Selección Argentina)"},{"key":"Resistencia al agua","value":"IPX7 totalmente sumergible"},{"key":"Cuchilla","value":"Cerámica Skin-Friendly anti-cortes"},{"key":"Base","value":"Soporte vertical de recarga USB"}]'::jsonb, TRUE, TRUE, TRUE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-vgr-v315-shaver', 'Afeitadora Rotativa VGR V-315 Men''s Shaver Triple Cabezal Magnético', 'vgr-v315-mens-shaver-triple-cabezal-magnetico', 'VGR-V315', 'Afeitadora rotativa de 3 cabezales flotantes magnéticos para afeitado suave al ras sin fricción.', 'El cabezal con acople magnético facilita la limpieza con solo desprenderlo hacia arriba. Cuchillas flotantes independientes que se adaptan a las líneas de la mandíbula y cuello para un corte ultra suave.', '{"_id":"cat-maquinas","title":"Máquinas de Corte & Trimmers","slug":"maquinas-corte-trimmers","description":"Clippers inalámbricas, trimmers de terminación, shavers de lámina y kits profesionales de marcas líderes.","icon":"Scissors","image":"/uploads/articulos/wahl-senior-cordless.jpeg","itemCount":12}'::jsonb, '{"_id":"b-vgr","name":"VGR Professional","slug":"vgr"}'::jsonb, '["/uploads/articulos/vgr-v315-shaver.jpeg"]'::jsonb, 'Caja con cable USB y cepillo limpiador', '[{"key":"Sistema","value":"Triple cabezal rotativo flotante"},{"key":"Acople","value":"Magnetic Suction desmontable"},{"key":"Batería","value":"Ion-Litio recargable USB"}]'::jsonb, TRUE, FALSE, FALSE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-wmark-ng8906', 'Afeitadora Shaver WMARK NG-8906 High Speed Barber Shaver 9500 RPM', 'wmark-ng8906-high-speed-barber-shaver-9500-rpm', 'WMK-NG8906', 'Shaver profesional de lámina doble de 9500 RPM, pantalla LCD con velocímetro y base de carga.', 'Herramienta indispensable para el acabado skin fade en barbería. Con una velocidad máxima de 9500 RPM y láminas hipoalergénicas doradas, rasura a cero sin irritar. Pantalla con indicación en tiempo real de porcentaje de batería y velocidad.', '{"_id":"cat-maquinas","title":"Máquinas de Corte & Trimmers","slug":"maquinas-corte-trimmers","description":"Clippers inalámbricas, trimmers de terminación, shavers de lámina y kits profesionales de marcas líderes.","icon":"Scissors","image":"/uploads/articulos/wahl-senior-cordless.jpeg","itemCount":12}'::jsonb, '{"_id":"b-wmark","name":"WMARK Professional","slug":"wmark"}'::jsonb, '["/uploads/articulos/wmark-ng8906-shaver.jpeg","/uploads/articulos/wmark-ng8906-shaver-2.jpeg"]'::jsonb, 'Caja cerrada con base de escritorio, cable USB y lámina de repuesto', '[{"key":"Potencia","value":"Motor magnético hasta 9500 RPM"},{"key":"Display","value":"Pantalla LCD digital completa"},{"key":"Accesorios","value":"Base cargadora de escritorio incluida"},{"key":"Láminas","value":"Doble lámina flotante dorada"}]'::jsonb, TRUE, TRUE, TRUE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-wmark-ng8634-kit', 'Kit Barbería WMARK NG-8634 Panther Edition (Clipper + Trimmer)', 'wmark-ng8634-kit-variable-barber-kit-panther', 'WMK-NG8634-KIT', 'Combo profesional completo de máquina de corte + trimmer de detalle con bases individuales y diseño Panther.', 'El kit definitivo para barberías. Incluye una clipper de corte pesado con cuchilla fade y una trimmer de terminación ultra nítida, ambas con bases de carga individuales para el puesto de trabajo. Diseño agresivo con relieve de pantera y motores de alto rendimiento.', '{"_id":"cat-maquinas","title":"Máquinas de Corte & Trimmers","slug":"maquinas-corte-trimmers","description":"Clippers inalámbricas, trimmers de terminación, shavers de lámina y kits profesionales de marcas líderes.","icon":"Scissors","image":"/uploads/articulos/wahl-senior-cordless.jpeg","itemCount":12}'::jsonb, '{"_id":"b-wmark","name":"WMARK Professional","slug":"wmark"}'::jsonb, '["/uploads/articulos/wmark-ng8634-barber-kit.jpeg"]'::jsonb, 'Caja kit duo x 2 máquinas con bases independientes', '[{"key":"Contenido","value":"1 Clipper + 1 Trimmer + 2 Bases"},{"key":"Cuchillas","value":"DLC Fade y Skeleton T-Blade"},{"key":"Batería","value":"Litio con carga independiente USB"}]'::jsonb, TRUE, TRUE, TRUE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-kemei-km2299', 'Trimmer Kemei KM-2299 Professional Hair Clipper / Trimmer', 'kemei-km2299-professional-hair-clipper-trimmer', 'KMI-KM2299', 'Trimmer liviana con cuchilla expuesta en T de 7000 RPM para contornos, patillas y terminaciones.', 'Una de las herramientas más solicitadas por su ergonomía y bajo peso. Su cabezal en T facilita la visión clara de la línea de corte en orejas, nuca y perfilado de barba.', '{"_id":"cat-maquinas","title":"Máquinas de Corte & Trimmers","slug":"maquinas-corte-trimmers","description":"Clippers inalámbricas, trimmers de terminación, shavers de lámina y kits profesionales de marcas líderes.","icon":"Scissors","image":"/uploads/articulos/wahl-senior-cordless.jpeg","itemCount":12}'::jsonb, '{"_id":"b-kemei","name":"Kemei Professional","slug":"kemei"}'::jsonb, '["/uploads/articulos/kemei-km2299-clipper.jpeg","/uploads/articulos/kemei-km2299-clipper-2.jpeg"]'::jsonb, 'Caja sellada con 3 peines guía + cargador USB', '[{"key":"Velocidad","value":"7000 RPM de corte continuo"},{"key":"Cuchilla","value":"Acero al carbono en T"},{"key":"Conectividad","value":"Carga rápida USB Type-C"}]'::jsonb, TRUE, FALSE, FALSE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-kemei-km2600', 'Máquina de Corte Kemei KM-2600 Cordless Precision Fade Clipper', 'kemei-km2600-cordless-precision-fade-clipper', 'KMI-KM2600', 'Clipper inalámbrica con cuchilla Stagger-tooth ''Crunch'', palanca de regulación y motor rotativo.', 'Clásico infaltable en barberías. Ofrece corte potente tanto en pelo seco como húmedo con cuchillas tipo Stagger-tooth que entregan cortes difuminados limpios sin líneas residuales.', '{"_id":"cat-maquinas","title":"Máquinas de Corte & Trimmers","slug":"maquinas-corte-trimmers","description":"Clippers inalámbricas, trimmers de terminación, shavers de lámina y kits profesionales de marcas líderes.","icon":"Scissors","image":"/uploads/articulos/wahl-senior-cordless.jpeg","itemCount":12}'::jsonb, '{"_id":"b-kemei","name":"Kemei Professional","slug":"kemei"}'::jsonb, '["/uploads/articulos/kemei-km2600-clipper.jpeg"]'::jsonb, 'Caja sellada con peines guía de 1.5 a 6 mm', '[{"key":"Batería","value":"Ion-Litio más de 60 min de corte"},{"key":"Cuchilla","value":"Stagger-Tooth Crunch Technology"},{"key":"Palanca","value":"Taper lever de regulación continua"}]'::jsonb, TRUE, FALSE, FALSE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-treet-platinum-100', 'Hojas de Afeitar Treet Platinum Super Stainless (Caja x 100 Filos)', 'hojas-de-afeitar-treet-platinum-caja-x-100', 'TRT-PLT-100', 'Hojas de acero inoxidable sueco con recubrimiento de platino y teflón para filo dulce y deslizamiento suave.', 'Los filos Treet Platinum son reconocidos por su corte suave que evita irritaciones en la piel del cliente. Cuentan con tratamiento anticorrosión y filo templado de altísima precisión para navajas de barbero.', '{"_id":"cat-tijeras","title":"Tijeras, Navajas & Filos","slug":"tijeras-filos-profesionales","description":"Tijeras de corte microdentadas, filo dulce japonés, navajas de barbero y hojas de afeitar Treet Platinum.","icon":"Sparkles","image":"/uploads/articulos/treet-platinum-100-pack.jpeg","itemCount":4}'::jsonb, '{"_id":"b-treet","name":"Treet Platinum","slug":"treet"}'::jsonb, '["/uploads/articulos/treet-platinum-100-pack.jpeg","/uploads/articulos/treet-platinum-100-londres.jpeg"]'::jsonb, 'Caja dispensadora exhibidora x 100 filos individuales', '[{"key":"Material","value":"Acero inoxidable sueco templado"},{"key":"Recubrimiento","value":"Platino & Teflon antifricción"},{"key":"Cantidad","value":"100 filos por caja"}]'::jsonb, TRUE, TRUE, FALSE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-treet-platinum-200', 'Hojas de Afeitar Treet Platinum Super Stainless (Pack Mayorista x 200)', 'hojas-de-afeitar-treet-platinum-pack-x-200', 'TRT-PLT-200', 'Pack mayorista de 200 hojas de afeitar Treet Platinum con precio diferencial por volumen.', 'Presentación ideal para distribuidores y barberías con alto volumen de afeitado semanal. Hojas envasadas en papel encerado individual que previene la humedad.', '{"_id":"cat-tijeras","title":"Tijeras, Navajas & Filos","slug":"tijeras-filos-profesionales","description":"Tijeras de corte microdentadas, filo dulce japonés, navajas de barbero y hojas de afeitar Treet Platinum.","icon":"Sparkles","image":"/uploads/articulos/treet-platinum-100-pack.jpeg","itemCount":4}'::jsonb, '{"_id":"b-treet","name":"Treet Platinum","slug":"treet"}'::jsonb, '["/uploads/articulos/treet-platinum-200-blades.jpeg"]'::jsonb, 'Pack cerrado mayorista x 200 filos (40 cajitas x 5 u.)', '[{"key":"Presentación","value":"Pack sellado x 200 filos"},{"key":"Uso","value":"Navajas tradicionales y shavettes"}]'::jsonb, TRUE, FALSE, FALSE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-navajas-custom', 'Navajas de Barbero Personalizadas Londress Series (Calavera, Oro, Joker)', 'navajas-de-barbero-personalizadas-londress-series', 'NVJ-PRO-CUST', 'Porta navajas de acero inoxidable con traba deslizante y mangos estilizados en motivos Calavera, Oro y Joker.', 'Navajas con excelente balance de peso y filo firme gracias a su sistema de inserción de medio filo con traba de seguridad. Mangos con diseños gráficos que resaltan en el puesto de trabajo.', '{"_id":"cat-tijeras","title":"Tijeras, Navajas & Filos","slug":"tijeras-filos-profesionales","description":"Tijeras de corte microdentadas, filo dulce japonés, navajas de barbero y hojas de afeitar Treet Platinum.","icon":"Sparkles","image":"/uploads/articulos/treet-platinum-100-pack.jpeg","itemCount":4}'::jsonb, '{"_id":"b-londress","name":"Londress Pro Series","slug":"londress-pro"}'::jsonb, '["/uploads/articulos/navajas-barber-custom.jpeg"]'::jsonb, 'Funda protectora plástica individual con cierre', '[{"key":"Sujeción","value":"Corredera de seguridad de acero inox"},{"key":"Variantes","value":"Calavera Grim Reaper, Oro Vintage, Joker"},{"key":"Compatibilidad","value":"Medio filo universal (Treet, Gillette, etc.)"}]'::jsonb, TRUE, TRUE, TRUE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-caja-mayorista', 'Caja Cerrada Mayorista Londress Barbería & Filos', 'caja-cerrada-mayorista-londress-barberia-filos', 'LND-BOX-MAY', 'Combo surtido para barberías: Tijeras profesionales de corte y pulir, packs Treet Platinum, cuchillas cerámicas y accesorios.', 'La opción más rentable para equipar o reponer insumos críticos. Incluye tijeras en fundas individuales, múltiples cajas de filos de afeitar Treet Platinum y cuchillas cerámicas de colores para máquinas de corte.', '{"_id":"cat-tijeras","title":"Tijeras, Navajas & Filos","slug":"tijeras-filos-profesionales","description":"Tijeras de corte microdentadas, filo dulce japonés, navajas de barbero y hojas de afeitar Treet Platinum.","icon":"Sparkles","image":"/uploads/articulos/treet-platinum-100-pack.jpeg","itemCount":4}'::jsonb, '{"_id":"b-londress","name":"Londress Pro Series","slug":"londress-pro"}'::jsonb, '["/uploads/articulos/caja-mayorista-barberia-londres.jpeg"]'::jsonb, 'Caja bulto cerrado surtido listo para despacho', '[{"key":"Contenido","value":"Tijeras, filos Treet, cuchillas cerámicas, palancas"},{"key":"Destino","value":"Barberías profesionales y salones"}]'::jsonb, TRUE, TRUE, TRUE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-dom-pelo-shaving', 'Gel de Afeitar Dom Pelo Shaving Gel Mentolado 500g', 'gel-de-afeitar-dom-pelo-shaving-gel-mentolado-500g', 'DMP-SHV-500', 'Gel de afeitar transparente de alto rendimiento que hidrata, refresca y permite ver la línea de corte con precisión.', 'Gel profesional formulado en Brasil para afeitado y diseño de contornos con navaja. Su consistencia transparente no obstruye la visibilidad, permitiendo dibujar líneas perfectas. Con extractos humectantes que calman la piel.', '{"_id":"cat-accesorios","title":"Accesorios, Capas & Barbería","slug":"accesorios-capas-barberia","description":"Capas WMARK, peines de carbono, papel de cuello Luke Paper, rociadores, aerosoles Andis Cool Care y lubricantes.","icon":"Package","image":"/uploads/articulos/capa-wmark-negra.jpeg","itemCount":11}'::jsonb, '{"_id":"b-dompelo","name":"Dom Pelo","slug":"dom-pelo"}'::jsonb, '["/uploads/articulos/dom-pelo-shaving-gel-500g.jpeg"]'::jsonb, 'Botella con bomba dosificadora x 500g', '[{"key":"Contenido neto","value":"500 gramos con dosificador"},{"key":"Textura","value":"Gel transparente lubricante"},{"key":"Efecto","value":"Frescura mentolada y anti-irritación"}]'::jsonb, TRUE, TRUE, TRUE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-l3vel3-aftershave', 'Colonia Post-Afeitado L3VEL3 Aftershave Cologne Vibrant 400ml', 'colonia-post-afeitado-l3vel3-aftershave-cologne-vibrant-400ml', 'LV3-AFT-400', 'Aftershave y fragancia 2 en 1 revitalizante e hidratante para todo tipo de piel.', 'La marca que eligen las mejores barberías del mundo. Refresca y revitaliza la piel instantáneamente luego del afeitado, desinfectando y cerrando los poros con una fragancia masculina duradera.', '{"_id":"cat-accesorios","title":"Accesorios, Capas & Barbería","slug":"accesorios-capas-barberia","description":"Capas WMARK, peines de carbono, papel de cuello Luke Paper, rociadores, aerosoles Andis Cool Care y lubricantes.","icon":"Package","image":"/uploads/articulos/capa-wmark-negra.jpeg","itemCount":11}'::jsonb, '{"_id":"b-l3vel3","name":"L3VEL3","slug":"l3vel3"}'::jsonb, '["/uploads/articulos/l3vel3-aftershave-vibrant.jpeg"]'::jsonb, 'Botella con atomizador spray de 400ml (13.5 fl oz)', '[{"key":"Fragancia","value":"Vibrant (Cítrica amaderada)"},{"key":"Volumen","value":"400 ml con atomizador"},{"key":"Origen","value":"Importado oficial L3VEL3"}]'::jsonb, TRUE, TRUE, TRUE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-infinity-locion', 'Loción Pós-Barba Infinity Look''s Hair Classic Barber Series Menthol 120ml', 'locion-pos-barba-infinity-classic-barber-menthol-120ml', 'INF-POS-120', 'Loción post afeitado mentolada que hidrata, refresca y acalma la piel reduciendo rojeces.', 'Fórmula astringente que proporciona una inmediata sensación de frescura tras el paso de la navaja o máquina. Su atomizador permite una aplicación higiénica y uniforme en cuello y mejillas.', '{"_id":"cat-accesorios","title":"Accesorios, Capas & Barbería","slug":"accesorios-capas-barberia","description":"Capas WMARK, peines de carbono, papel de cuello Luke Paper, rociadores, aerosoles Andis Cool Care y lubricantes.","icon":"Package","image":"/uploads/articulos/capa-wmark-negra.jpeg","itemCount":11}'::jsonb, '{"_id":"b-infinity","name":"Infinity Look''s Hair","slug":"infinity"}'::jsonb, '["/uploads/articulos/infinity-locion-posbarba-menthol.jpeg","/uploads/articulos/infinity-locion-posbarba-2.jpeg"]'::jsonb, 'Frasco spray atomizador de 120ml', '[{"key":"Contenido","value":"120 ml atomizador"},{"key":"Efecto","value":"Calmante, refrescante y antiséptico"}]'::jsonb, TRUE, FALSE, FALSE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-cuchillas-camo', 'Cuchillas Cerámicas Móviles Fade Camouflage (Verde, Azul, Rojo)', 'cuchillas-ceramicas-moviles-fade-camouflage', 'CCH-CER-CAMO', 'Cuchilla móvil de cerámica de zirconio con estampado camuflado en verde, azul o rojo. Mantiene la máquina fría.', 'Cuchilla de repuesto para máquinas de corte Wahl, Kemei, VGR, Gamma+ y Babyliss. La cerámica de zirconio no absorbe calor, asegurando que la máquina trabaje fría durante horas sin quemar la piel del cliente.', '{"_id":"cat-accesorios","title":"Accesorios, Capas & Barbería","slug":"accesorios-capas-barberia","description":"Capas WMARK, peines de carbono, papel de cuello Luke Paper, rociadores, aerosoles Andis Cool Care y lubricantes.","icon":"Package","image":"/uploads/articulos/capa-wmark-negra.jpeg","itemCount":11}'::jsonb, '{"_id":"b-londress","name":"Londress Pro Series","slug":"londress-pro"}'::jsonb, '["/uploads/articulos/cuchilla-ceramica-verde-camo.jpeg","/uploads/articulos/cuchilla-ceramica-azul-camo.jpeg","/uploads/articulos/cuchilla-ceramica-roja-camo.jpeg"]'::jsonb, 'Estuche acrílico individual con esponja amortiguadora', '[{"key":"Material","value":"Cerámica de Zirconio Zirconia"},{"key":"Compatibilidad","value":"Wahl Senior, Magic Clip, Kemei 2600, VGR"},{"key":"Variantes","value":"Verde Camo, Azul Camo, Rojo Camo"}]'::jsonb, TRUE, TRUE, TRUE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-wahl-peine-05', 'Peine Guía WAHL Premium Cutting Guide # 1/2 con Traba Metálica 1.5mm', 'peine-guia-wahl-premium-cutting-guide-medio-1-5mm', 'WHL-PG-05', 'Peine de precisión número 1/2 (1.5mm - 1/16") de resina de ingeniería con traba metálica de fijación segura.', 'El peine indispensable para degradados cero y transiciones limpias. Su traba de acero templado impide que el peine se desprenda accidentalmente en medio de un pase de máquina.', '{"_id":"cat-accesorios","title":"Accesorios, Capas & Barbería","slug":"accesorios-capas-barberia","description":"Capas WMARK, peines de carbono, papel de cuello Luke Paper, rociadores, aerosoles Andis Cool Care y lubricantes.","icon":"Package","image":"/uploads/articulos/capa-wmark-negra.jpeg","itemCount":11}'::jsonb, '{"_id":"b-wahl","name":"Wahl Professional","slug":"wahl"}'::jsonb, '["/uploads/articulos/wahl-peine-guia-premium-05.jpeg","/uploads/articulos/wahl-peine-guia-premium-05-2.jpeg"]'::jsonb, 'Blíster oficial sellado Wahl #3354-1000', '[{"key":"Medida","value":"# 1/2 (1.5 mm - 1/16 pulgada)"},{"key":"Fijación","value":"Secure Fit Metal Clip"},{"key":"Compatibilidad","value":"Línea Wahl 5-Star y estándar"}]'::jsonb, TRUE, FALSE, FALSE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-capa-wmark', 'Capa de Barbería WMARK Professional Impermeable y Antiestática', 'capa-de-barberia-wmark-professional-impermeable-antiestatica', 'WMK-CAP-01', 'Capa de corte de gran cobertura en base negra o blanca con W roja, tela antiestática que no retiene cabellos.', 'Diseño premium para barberías contemporáneas. Confeccionada con tela sedosa repelente de agua y químicos de tinte, con cuello elástico regulable con ganchos de acero que se adapta a cualquier tamaño de cuello.', '{"_id":"cat-accesorios","title":"Accesorios, Capas & Barbería","slug":"accesorios-capas-barberia","description":"Capas WMARK, peines de carbono, papel de cuello Luke Paper, rociadores, aerosoles Andis Cool Care y lubricantes.","icon":"Package","image":"/uploads/articulos/capa-wmark-negra.jpeg","itemCount":11}'::jsonb, '{"_id":"b-wmark","name":"WMARK Professional","slug":"wmark"}'::jsonb, '["/uploads/articulos/capa-wmark-negra.jpeg","/uploads/articulos/capa-wmark-blanca.jpeg","/uploads/articulos/capa-wmark-negra-2.jpeg"]'::jsonb, 'Bolsa sellada individual / Pack x 6 unidades', '[{"key":"Medidas","value":"145 x 165 cm (cobertura total de sillón)"},{"key":"Cierre","value":"Ganchos metálicos reforzados"},{"key":"Modelos","value":"Negra con rojo / Blanca con rojo"}]'::jsonb, TRUE, TRUE, TRUE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-peines-carbono', 'Set de Peines de Corte de Carbono Antiestático & Peine Metálico Dorado', 'set-peines-carbono-antiestatico-peine-metalico-dorado', 'PN-CRB-GLD', 'Peine de carbono resistente a químicos y calor + peine de precisión bañado en oro con orificios medidores.', 'Diseñados para cortes con máquina sobre peine (clipper over comb) y trabajos de precisión con tijera. Dientes pulidos a mano que no raspan el cuero cabelludo y otorgan tensión uniforme.', '{"_id":"cat-accesorios","title":"Accesorios, Capas & Barbería","slug":"accesorios-capas-barberia","description":"Capas WMARK, peines de carbono, papel de cuello Luke Paper, rociadores, aerosoles Andis Cool Care y lubricantes.","icon":"Package","image":"/uploads/articulos/capa-wmark-negra.jpeg","itemCount":11}'::jsonb, '{"_id":"b-londress","name":"Londress Pro Series","slug":"londress-pro"}'::jsonb, '["/uploads/articulos/peines-carbono-dorado.jpeg","/uploads/articulos/peine-carbono-profesional.jpeg"]'::jsonb, 'Blíster individual de protección', '[{"key":"Material","value":"Fibra de carbono + Aleación dorada"},{"key":"Resistencia","value":"Térmica hasta 220°C"}]'::jsonb, TRUE, FALSE, FALSE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-luke-paper', 'Papel Cuello Elástico Autoadhesivo Luke Paper Professional', 'papel-cuello-elastico-autoadhesivo-luke-paper', 'LUK-NCK-100', 'Banda elástica impermeable de celulosa suave con adhesivo frontal para máxima higiene entre capa y piel.', 'Indispensable para cumplir con estándares de higiene en peluquerías y barberías. Evita el contacto directo de la capa con la piel del cliente y retiene restos de cabellos sueltos.', '{"_id":"cat-accesorios","title":"Accesorios, Capas & Barbería","slug":"accesorios-capas-barberia","description":"Capas WMARK, peines de carbono, papel de cuello Luke Paper, rociadores, aerosoles Andis Cool Care y lubricantes.","icon":"Package","image":"/uploads/articulos/capa-wmark-negra.jpeg","itemCount":11}'::jsonb, '{"_id":"b-londress","name":"Londress Pro Series","slug":"londress-pro"}'::jsonb, '["/uploads/articulos/luke-paper-cuello.jpeg"]'::jsonb, 'Rollo de 100 tiras / Tira de 5 rollos (500 servicios)', '[{"key":"Rendimiento","value":"100 servicios por rollo"},{"key":"Propiedades","value":"Impermeable, elástico y autoadhesivo"}]'::jsonb, TRUE, FALSE, FALSE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-rociadores-barber', 'Rociador Pulverizador Barber Design Pico Regulable', 'rociador-pulverizador-barber-design-pico-regulable', 'ROC-PLV-BAR', 'Botella pulverizadora transparente con motivos de barbería, pico giratorio de bruma fina a chorro directo.', 'Gatillo ergonómico de retorno rápido que previene la fatiga en las manos. Cuerpo transparente que permite visualizar el nivel de agua o loción capilar.', '{"_id":"cat-accesorios","title":"Accesorios, Capas & Barbería","slug":"accesorios-capas-barberia","description":"Capas WMARK, peines de carbono, papel de cuello Luke Paper, rociadores, aerosoles Andis Cool Care y lubricantes.","icon":"Package","image":"/uploads/articulos/capa-wmark-negra.jpeg","itemCount":11}'::jsonb, '{"_id":"b-londress","name":"Londress Pro Series","slug":"londress-pro"}'::jsonb, '["/uploads/articulos/rociadores-barber-transparentes.jpeg"]'::jsonb, 'Bolsa protectora / Caja mayorista x 12 u.', '[{"key":"Capacidad","value":"300 ml"},{"key":"Boquilla","value":"Regulable Bruma / Chorro"}]'::jsonb, TRUE, FALSE, FALSE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-cepillo-fade', 'Cepillo Fade Brush de Cerdas Suaves para Limpieza de Degradados', 'cepillo-fade-brush-cerdas-suaves-degradados', 'CEP-FAD-BLK', 'Cepillo de mano ergonómico con cerdas compactas que barren el polvillo de pelo sin raspar la piel del cliente.', 'Herramienta fundamental para verificar la precisión del difuminado y la sombra en cada paso del degradado con máquina o navaja.', '{"_id":"cat-accesorios","title":"Accesorios, Capas & Barbería","slug":"accesorios-capas-barberia","description":"Capas WMARK, peines de carbono, papel de cuello Luke Paper, rociadores, aerosoles Andis Cool Care y lubricantes.","icon":"Package","image":"/uploads/articulos/capa-wmark-negra.jpeg","itemCount":11}'::jsonb, '{"_id":"b-londress","name":"Londress Pro Series","slug":"londress-pro"}'::jsonb, '["/uploads/articulos/cepillos-fade-brush.jpeg"]'::jsonb, 'Pack mayorista x 6 unidades / Unitario', '[{"key":"Cerdas","value":"Nylon balanceado suave"},{"key":"Mango","value":"Plástico inyectado anatómico negro"}]'::jsonb, TRUE, FALSE, FALSE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-andis-cool-care', 'Andis Cool Care Plus 5 in 1 Aerosol para Cuchillas 439g', 'andis-cool-care-plus-5-in-1-aerosol-cuchillas-439g', 'AND-CCL-439', 'El aerosol 5 en 1 líder en salones: enfría al instante, desinfecta, lubrica las hojas, limpia residuos y previene la corrosión.', 'Extiende la vida útil de tus cuchillas Wahl, Andis, Babyliss o Kemei. Rociar directamente sobre la cuchilla en movimiento para un enfriamiento instantáneo durante jornadas extensas de salón.', '{"_id":"cat-accesorios","title":"Accesorios, Capas & Barbería","slug":"accesorios-capas-barberia","description":"Capas WMARK, peines de carbono, papel de cuello Luke Paper, rociadores, aerosoles Andis Cool Care y lubricantes.","icon":"Package","image":"/uploads/articulos/capa-wmark-negra.jpeg","itemCount":11}'::jsonb, '{"_id":"b-andis","name":"Andis USA","slug":"andis"}'::jsonb, '["/uploads/articulos/andis-cool-care-plus.jpeg"]'::jsonb, 'Lata aerosol de 439g (15.5 oz) / Caja mayorista x 12 unidades', '[{"key":"Funciones","value":"Refrigerante, Desinfectante, Lubricante, Limpiador y Anti-óxido"},{"key":"Contenido","value":"439 gramos (15.5 oz)"},{"key":"Origen","value":"Made in USA"}]'::jsonb, TRUE, TRUE, FALSE) ON CONFLICT (_id) DO NOTHING;
INSERT INTO products (_id, name, slug, sku, "shortDescription", description, category, brand, images, presentation, specifications, "inStock", featured, "isNew") VALUES ('prod-secador-tucano', 'Secador Profesional Tucano HairDryer 8600 Watt Motor AC Italiano', 'secador-profesional-tucano-hairdryer-8600w-motor-ac', 'TUC-HDR-8600', 'Motor italiano AC de larga vida útil, 6 combinaciones de temperatura/velocidad y tecnología de secado 50% más rápido.', 'Flujo de aire concentrado y parejo para brushing profesional y alisados térmicos. Reduce el frizz sellando la cutícula capilar gracias a su emisión térmica infrarroja balanceada.', '{"_id":"cat-secadores","title":"Secadores & Herramientas Térmicas","slug":"secadores-herramientas-termicas","description":"Secadores de alto rendimiento con motor italiano, planchas alisadoras de titanio cerámico y bucleadoras.","icon":"Wind","image":"/uploads/articulos/secador-tucano-8600w.jpeg","itemCount":1}'::jsonb, '{"_id":"b-tucano","name":"Tucano Hair Tools","slug":"tucano"}'::jsonb, '["/uploads/articulos/secador-tucano-8600w.jpeg"]'::jsonb, 'Caja individual con 2 boquillas concentradoras de aire', '[{"key":"Potencia","value":"8600 W alto rendimiento"},{"key":"Motor","value":"Italian AC Motor de uso intensivo"},{"key":"Ajustes","value":"6 combinaciones de calor y velocidad + botón frío"}]'::jsonb, TRUE, TRUE, TRUE) ON CONFLICT (_id) DO NOTHING;
